// <auto-generated/>
#nullable enable
#pragma warning disable CS0618, CS1591, CA2255

[assembly: global::Ion.Extensions.Networking.NetworkTypesAssemblyAttribute(typeof(global::Ion.Generated.Networking.NetworkTypes_NetTest))]

namespace Ion.Generated.Networking
{
	/// <summary>The network types of this assembly (generated by Ion.Extensions.Networking.Generators).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Extensions.Networking.Generators", "1.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	public static class NetworkTypes_NetTest
	{
		private static bool _registered;

		[global::System.Runtime.CompilerServices.ModuleInitializer]
		internal static void Initialize() => Register();

		/// <summary>Registers this assembly's replicated components and network messages, and those of its references.</summary>
		public static void Register()
		{
			if (_registered) return;
			_registered = true;
			global::Ion.Extensions.Ecs.EcsComponents.Register<global::Game.Health>();
			global::Ion.Extensions.Networking.NetworkRegistry.Register(new global::Ion.Extensions.Networking.ReplicatedTypeInfo<global::Game.Health>("Game.Health", "Current:int;Max:int", new S_Game_Health(), (global::Ion.Extensions.Networking.Authority)0, false, false));
			global::Ion.Extensions.Ecs.EcsComponents.Register<global::Game.Body>();
			global::Ion.Extensions.Networking.NetworkRegistry.Register(new global::Ion.Extensions.Networking.ReplicatedTypeInfo<global::Game.Body>("Game.Body", "Position:System.Numerics.Vector3;Rotation:System.Numerics.Quaternion;Team:Game.Team;Inner:{A:int;B:System.Numerics.Vector2};Name:Ion.Extensions.Networking.FixedString32;Target:Ion.Extensions.Networking.NetworkId", new S_Game_Body(), (global::Ion.Extensions.Networking.Authority)1, true, true));
			global::Ion.Extensions.Networking.NetworkRegistry.Register(new global::Ion.Extensions.Networking.MessageTypeInfo<global::Game.Input>("Game.Input", "Move:System.Numerics.Vector2;Fire:bool", new S_Game_Input(), (global::Ion.Extensions.Networking.Delivery)0, (global::Ion.Extensions.Networking.MessageDirection)1));
		}

		private sealed class S_Game_Health : global::Ion.Extensions.Networking.NetSerializer<global::Game.Health>
		{
			public override int MaxSize => 8;

			public override void Write(ref global::Ion.Extensions.Networking.NetWriter w, in global::Game.Health v)
			{
				w.WriteInt32(v.Current);
				w.WriteInt32(v.Max);
			}

			public override global::Game.Health Read(ref global::Ion.Extensions.Networking.NetReader r)
			{
				var m0 = r.ReadInt32();
				var m1 = r.ReadInt32();
				return default(global::Game.Health) with { Current = m0, Max = m1 };
			}

			public override bool WriteDelta(ref global::Ion.Extensions.Networking.NetWriter w, in global::Game.Health b, in global::Game.Health v)
			{
				ulong mask = 0;
				if (!(b.Current == v.Current)) mask |= 1UL << 0;
				if (!(b.Max == v.Max)) mask |= 1UL << 1;
				if (mask == 0) return false;
				w.WriteVarUInt64(mask);
				if ((mask & (1UL << 0)) != 0) w.WriteInt32(v.Current);
				if ((mask & (1UL << 1)) != 0) w.WriteInt32(v.Max);
				return true;
			}

			public override global::Game.Health ReadDelta(ref global::Ion.Extensions.Networking.NetReader r, in global::Game.Health b)
			{
				var mask = r.ReadVarUInt64();
				if ((mask >> 2) != 0) r.Fail();
				var m0 = (mask & (1UL << 0)) != 0 ? r.ReadInt32() : b.Current;
				var m1 = (mask & (1UL << 1)) != 0 ? r.ReadInt32() : b.Max;
				return b with { Current = m0, Max = m1 };
			}

			public override bool Equal(in global::Game.Health a, in global::Game.Health b) => a.Current == b.Current && a.Max == b.Max;
		}

		private sealed class S_Game_Body : global::Ion.Extensions.Networking.NetSerializer<global::Game.Body>
		{
			public override int MaxSize => 78;

			public override void Write(ref global::Ion.Extensions.Networking.NetWriter w, in global::Game.Body v)
			{
				w.WriteVector3(v.Position);
				w.WriteQuaternion(v.Rotation);
				w.WriteByte((byte)v.Team);
				W_Game_Inner(ref w, v.Inner);
				w.WriteFixedString32(v.Name);
				w.WriteNetworkId(v.Target);
			}

			public override global::Game.Body Read(ref global::Ion.Extensions.Networking.NetReader r)
			{
				var m0 = r.ReadVector3();
				var m1 = r.ReadQuaternion();
				var m2 = (global::Game.Team)r.ReadByte();
				var m3 = R_Game_Inner(ref r);
				var m4 = r.ReadFixedString32();
				var m5 = r.ReadNetworkId();
				return default(global::Game.Body) with { Position = m0, Rotation = m1, Team = m2, Inner = m3, Name = m4, Target = m5 };
			}

			public override bool WriteDelta(ref global::Ion.Extensions.Networking.NetWriter w, in global::Game.Body b, in global::Game.Body v)
			{
				ulong mask = 0;
				if (!(global::Ion.Extensions.Networking.NetCompare.Same(b.Position, v.Position))) mask |= 1UL << 0;
				if (!(global::Ion.Extensions.Networking.NetCompare.Same(b.Rotation, v.Rotation))) mask |= 1UL << 1;
				if (!(b.Team == v.Team)) mask |= 1UL << 2;
				if (!(E_Game_Inner(b.Inner, v.Inner))) mask |= 1UL << 3;
				if (!(b.Name.Equals(v.Name))) mask |= 1UL << 4;
				if (!(b.Target == v.Target)) mask |= 1UL << 5;
				if (mask == 0) return false;
				w.WriteVarUInt64(mask);
				if ((mask & (1UL << 0)) != 0) w.WriteVector3(v.Position);
				if ((mask & (1UL << 1)) != 0) w.WriteQuaternion(v.Rotation);
				if ((mask & (1UL << 2)) != 0) w.WriteByte((byte)v.Team);
				if ((mask & (1UL << 3)) != 0) W_Game_Inner(ref w, v.Inner);
				if ((mask & (1UL << 4)) != 0) w.WriteFixedString32(v.Name);
				if ((mask & (1UL << 5)) != 0) w.WriteNetworkId(v.Target);
				return true;
			}

			public override global::Game.Body ReadDelta(ref global::Ion.Extensions.Networking.NetReader r, in global::Game.Body b)
			{
				var mask = r.ReadVarUInt64();
				if ((mask >> 6) != 0) r.Fail();
				var m0 = (mask & (1UL << 0)) != 0 ? r.ReadVector3() : b.Position;
				var m1 = (mask & (1UL << 1)) != 0 ? r.ReadQuaternion() : b.Rotation;
				var m2 = (mask & (1UL << 2)) != 0 ? (global::Game.Team)r.ReadByte() : b.Team;
				var m3 = (mask & (1UL << 3)) != 0 ? R_Game_Inner(ref r) : b.Inner;
				var m4 = (mask & (1UL << 4)) != 0 ? r.ReadFixedString32() : b.Name;
				var m5 = (mask & (1UL << 5)) != 0 ? r.ReadNetworkId() : b.Target;
				return b with { Position = m0, Rotation = m1, Team = m2, Inner = m3, Name = m4, Target = m5 };
			}

			public override bool Equal(in global::Game.Body a, in global::Game.Body b) => global::Ion.Extensions.Networking.NetCompare.Same(a.Position, b.Position) && global::Ion.Extensions.Networking.NetCompare.Same(a.Rotation, b.Rotation) && a.Team == b.Team && E_Game_Inner(a.Inner, b.Inner) && a.Name.Equals(b.Name) && a.Target == b.Target;

			public override global::Game.Body Interpolate(in global::Game.Body a, in global::Game.Body b, float t) => b with { Position = global::Ion.Extensions.Networking.NetLerp.Lerp(a.Position, b.Position, t), Rotation = global::Ion.Extensions.Networking.NetLerp.Lerp(a.Rotation, b.Rotation, t), Team = (t < 0.5f ? a.Team : b.Team), Inner = L_Game_Inner(a.Inner, b.Inner, t), Name = (t < 0.5f ? a.Name : b.Name), Target = (t < 0.5f ? a.Target : b.Target) };
		}

		private sealed class S_Game_Input : global::Ion.Extensions.Networking.NetSerializer<global::Game.Input>
		{
			public override int MaxSize => 9;

			public override void Write(ref global::Ion.Extensions.Networking.NetWriter w, in global::Game.Input v)
			{
				w.WriteVector2(v.Move);
				w.WriteBool(v.Fire);
			}

			public override global::Game.Input Read(ref global::Ion.Extensions.Networking.NetReader r)
			{
				var m0 = r.ReadVector2();
				var m1 = r.ReadBool();
				return default(global::Game.Input) with { Move = m0, Fire = m1 };
			}

			public override bool WriteDelta(ref global::Ion.Extensions.Networking.NetWriter w, in global::Game.Input b, in global::Game.Input v)
			{
				ulong mask = 0;
				if (!(global::Ion.Extensions.Networking.NetCompare.Same(b.Move, v.Move))) mask |= 1UL << 0;
				if (!(b.Fire == v.Fire)) mask |= 1UL << 1;
				if (mask == 0) return false;
				w.WriteVarUInt64(mask);
				if ((mask & (1UL << 0)) != 0) w.WriteVector2(v.Move);
				if ((mask & (1UL << 1)) != 0) w.WriteBool(v.Fire);
				return true;
			}

			public override global::Game.Input ReadDelta(ref global::Ion.Extensions.Networking.NetReader r, in global::Game.Input b)
			{
				var mask = r.ReadVarUInt64();
				if ((mask >> 2) != 0) r.Fail();
				var m0 = (mask & (1UL << 0)) != 0 ? r.ReadVector2() : b.Move;
				var m1 = (mask & (1UL << 1)) != 0 ? r.ReadBool() : b.Fire;
				return b with { Move = m0, Fire = m1 };
			}

			public override bool Equal(in global::Game.Input a, in global::Game.Input b) => global::Ion.Extensions.Networking.NetCompare.Same(a.Move, b.Move) && a.Fire == b.Fire;
		}

		private static void W_Game_Inner(ref global::Ion.Extensions.Networking.NetWriter w, in global::Game.Inner v)
		{
			w.WriteInt32(v.A);
			w.WriteVector2(v.B);
		}

		private static global::Game.Inner R_Game_Inner(ref global::Ion.Extensions.Networking.NetReader r)
		{
			var m0 = r.ReadInt32();
			var m1 = r.ReadVector2();
			return default(global::Game.Inner) with { A = m0, B = m1 };
		}
		private static bool E_Game_Inner(in global::Game.Inner a, in global::Game.Inner b) => a.A == b.A && global::Ion.Extensions.Networking.NetCompare.Same(a.B, b.B);
		private static global::Game.Inner L_Game_Inner(in global::Game.Inner a, in global::Game.Inner b, float t) => b with { A = (t < 0.5f ? a.A : b.A), B = global::Ion.Extensions.Networking.NetLerp.Lerp(a.B, b.B, t) };
	}
}
