// <auto-generated/>
// Generated by the Ion event generator (Ion.Generators). Do not edit.
#nullable enable
// The interceptors of Emit take 'in' parameters without the modreq(InAttribute) of the interface method they intercept.
#pragma warning disable CS9154

[assembly: global::Ion.EventUsageAttribute(typeof(global::Hit), (global::Ion.EventUsage)15)] // emitted in a loop in FixedUpdate or Update, read; capacity 256
[assembly: global::Ion.EventUsageAttribute(typeof(global::Scored), (global::Ion.EventUsage)15)] // emitted in a loop in FixedUpdate or Update, read; capacity 256
[assembly: global::Ion.EventUsageAttribute(typeof(global::Tick), (global::Ion.EventUsage)7)] // emitted in FixedUpdate or Update, read; capacity 64

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>
	/// The event bus of this application: one typed channel per event type it (or an Ion assembly it references) uses,
	/// with compile-time ids. Types it does not list get a channel from the runtime bus on first use.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class GeneratedEventBus : global::Ion.EventBus, global::Ion.IEvents
	{
		/// <summary>Id 1: <c>Hit</c> (emitted in a loop in FixedUpdate or Update, read; capacity 256).</summary>
		public readonly global::Ion.EventChannel<global::Hit> E1;
		/// <summary>Id 2: <c>ExitGameEvent</c> (read; capacity 4).</summary>
		public readonly global::Ion.EventChannel<global::Ion.ExitGameEvent> E2;
		/// <summary>Id 3: <c>ChangeSceneEvent</c> (read; capacity 4).</summary>
		public readonly global::Ion.EventChannel<global::Ion.Extensions.Scenes.ChangeSceneEvent> E3;
		/// <summary>Id 4: <c>Scored</c> (emitted in a loop in FixedUpdate or Update, read; capacity 256).</summary>
		public readonly global::Ion.EventChannel<global::Scored> E4;
		/// <summary>Id 5: <c>Tick</c> (emitted in FixedUpdate or Update, read; capacity 64).</summary>
		public readonly global::Ion.EventChannel<global::Tick> E5;

		private static bool _idsAssigned;

		public GeneratedEventBus(global::Ion.ILoopContext? loop) : base(loop)
		{
			AssignIds();
			E1 = Register<global::Hit>(256);
			E2 = Register<global::Ion.ExitGameEvent>(4);
			E3 = Register<global::Ion.Extensions.Scenes.ChangeSceneEvent>(4);
			E4 = Register<global::Scored>(256);
			E5 = Register<global::Tick>(64);
		}

		/// <summary>Gives every event type of this bus its compile-time id (<see cref="global::Ion.EventId{T}"/>).</summary>
		public static void AssignIds()
		{
			if (_idsAssigned) return;
			_idsAssigned = true;
			global::Ion.EventId<global::Hit>.TryAssign(1);
			global::Ion.EventId<global::Ion.ExitGameEvent>.TryAssign(2);
			global::Ion.EventId<global::Ion.Extensions.Scenes.ChangeSceneEvent>.TryAssign(3);
			global::Ion.EventId<global::Scored>.TryAssign(4);
			global::Ion.EventId<global::Tick>.TryAssign(5);
		}

		/// <summary>Installs this bus on <paramref name="builder"/>.</summary>
		public static global::Ion.IonApplicationBuilder Install(global::Ion.IonApplicationBuilder builder)
		{
			AssignIds();
			return builder.UseEventBus(static loop => new GeneratedEventBus(loop));
		}

		void global::Ion.IEvents.Emit<T>(in T e)
		{
			if (typeof(T) == typeof(global::Hit)) { E1.Emit(in global::System.Runtime.CompilerServices.Unsafe.As<T, global::Hit>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef(in e))); return; }
			if (typeof(T) == typeof(global::Ion.ExitGameEvent)) { E2.Emit(in global::System.Runtime.CompilerServices.Unsafe.As<T, global::Ion.ExitGameEvent>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef(in e))); return; }
			if (typeof(T) == typeof(global::Ion.Extensions.Scenes.ChangeSceneEvent)) { E3.Emit(in global::System.Runtime.CompilerServices.Unsafe.As<T, global::Ion.Extensions.Scenes.ChangeSceneEvent>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef(in e))); return; }
			if (typeof(T) == typeof(global::Scored)) { E4.Emit(in global::System.Runtime.CompilerServices.Unsafe.As<T, global::Scored>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef(in e))); return; }
			if (typeof(T) == typeof(global::Tick)) { E5.Emit(in global::System.Runtime.CompilerServices.Unsafe.As<T, global::Tick>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef(in e))); return; }
			Emit(in e);
		}

		global::Ion.EventReader<T> global::Ion.IEvents.Reader<T>()
		{
			if (typeof(T) == typeof(global::Hit)) { var reader = E1.Reader(); return global::System.Runtime.CompilerServices.Unsafe.As<global::Ion.EventReader<global::Hit>, global::Ion.EventReader<T>>(ref reader); }
			if (typeof(T) == typeof(global::Ion.ExitGameEvent)) { var reader = E2.Reader(); return global::System.Runtime.CompilerServices.Unsafe.As<global::Ion.EventReader<global::Ion.ExitGameEvent>, global::Ion.EventReader<T>>(ref reader); }
			if (typeof(T) == typeof(global::Ion.Extensions.Scenes.ChangeSceneEvent)) { var reader = E3.Reader(); return global::System.Runtime.CompilerServices.Unsafe.As<global::Ion.EventReader<global::Ion.Extensions.Scenes.ChangeSceneEvent>, global::Ion.EventReader<T>>(ref reader); }
			if (typeof(T) == typeof(global::Scored)) { var reader = E4.Reader(); return global::System.Runtime.CompilerServices.Unsafe.As<global::Ion.EventReader<global::Scored>, global::Ion.EventReader<T>>(ref reader); }
			if (typeof(T) == typeof(global::Tick)) { var reader = E5.Reader(); return global::System.Runtime.CompilerServices.Unsafe.As<global::Ion.EventReader<global::Tick>, global::Ion.EventReader<T>>(ref reader); }
			return Reader<T>();
		}
	}

	/// <summary>Installs the generated event bus, and routes this assembly's event calls to its typed channels.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonEventInterceptors
	{
		// Program.cs(91,17): CreateBuilder, installs the generated event bus
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Aar7ZLsoOxLUY2EmzphZnh8JAABQcm9ncmFtLmNz")]
		public static global::Ion.IonApplicationBuilder CreateBuilder_0(string[] args) =>
			GeneratedEventBus.Install(global::Ion.IonApplication.CreateBuilder(args));

		// Program.cs(32,31): Emit<Hit>
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Aar7ZLsoOxLUY2EmzphZnoYDAABQcm9ncmFtLmNz")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static void Emit_0(this global::Ion.IEvents receiver, in global::Hit e)
		{
			if (receiver is GeneratedEventBus bus) bus.E1.Emit(in e);
			else receiver.Emit(in e);
		}

		// Program.cs(38,26): Emit<Tick>
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Aar7ZLsoOxLUY2EmzphZnvgDAABQcm9ncmFtLmNz")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static void Emit_1(this global::Ion.IEvents events)
		{
			if (events is GeneratedEventBus bus) bus.E5.Emit(default(global::Tick));
			else global::Ion.EventsExtensions.Emit<global::Tick>(events);
		}

		// Program.cs(45,35): Reader<Hit>
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Aar7ZLsoOxLUY2EmzphZnrEEAABQcm9ncmFtLmNz")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static global::Ion.EventReader<global::Hit> Reader_2(this global::Ion.IEvents receiver) =>
			receiver is GeneratedEventBus bus ? bus.E1.Reader() : receiver.Reader<global::Hit>();

		// Program.cs(53,4): Emit<Scored>
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Aar7ZLsoOxLUY2EmzphZnm4FAABQcm9ncmFtLmNz")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static void Emit_3(this global::Ion.IEvents receiver, in global::Scored e)
		{
			if (receiver is GeneratedEventBus bus) bus.E4.Emit(in e);
			else receiver.Emit(in e);
		}

		// Program.cs(60,40): Reader<Scored>
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Aar7ZLsoOxLUY2EmzphZnu8FAABQcm9ncmFtLmNz")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static global::Ion.EventReader<global::Scored> Reader_4(this global::Ion.IEvents receiver) =>
			receiver is GeneratedEventBus bus ? bus.E4.Reader() : receiver.Reader<global::Scored>();

		// Program.cs(61,37): Reader<Tick>
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Aar7ZLsoOxLUY2EmzphZniwGAABQcm9ncmFtLmNz")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static global::Ion.EventReader<global::Tick> Reader_5(this global::Ion.IEvents receiver) =>
			receiver is GeneratedEventBus bus ? bus.E5.Reader() : receiver.Reader<global::Tick>();

		// Program.cs(62,40): Reader<Hit>
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Aar7ZLsoOxLUY2EmzphZnmoGAABQcm9ncmFtLmNz")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static global::Ion.EventReader<global::Hit> Reader_6(this global::Ion.IEvents receiver) =>
			receiver is GeneratedEventBus bus ? bus.E1.Reader() : receiver.Reader<global::Hit>();
	}
}
