// <auto-generated/>
// Generated by the Ion event generator (Ion.Generators). Do not edit.
#nullable enable
// The interceptors of Emit take 'in' parameters without the modreq(InAttribute) of the interface method they intercept.
#pragma warning disable CS9154

[assembly: global::Ion.EventUsageAttribute(typeof(global::Plugin.PluginInternal), (global::Ion.EventUsage)7)] // emitted in FixedUpdate or Update, read; capacity 64
[assembly: global::Ion.EventUsageAttribute(typeof(global::Plugin.PluginScored), (global::Ion.EventUsage)13)] // emitted in a loop in FixedUpdate or Update; capacity 256
