// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators). Do not edit.
#nullable enable
#pragma warning disable CS0618 // Legacy middleware APIs are intercepted too.

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonInterceptors
	{
		// Program.cs(31,3): UseSystem Counter (TestApp#0)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "he2bqA0SwR8+n1kI4VSMqDMDAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_0(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S0, "TestApp#0");
			return app;
		}

		// Program.cs(32,2): Init function App.lambda() (TestApp#1)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "he2bqA0SwR8+n1kI4VSMqE4DAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication Init_1(this global::Ion.IIonApplication builder, global::System.Action<global::Ion.GameTime> step, int order, string? name)
		{
			builder.Schedule.AddFunction(global::Ion.Stage.Init, step, global::System.Type.EmptyTypes, _ => global::Ion.StepAdapters.FromFunction(step), order, name ?? "App.lambda()", global::System.Type.EmptyTypes, global::System.Type.EmptyTypes, "TestApp#1");
			return builder;
		}

		// Program.cs(33,2): Update function App.lambda(Counter) (TestApp#2)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "he2bqA0SwR8+n1kI4VSMqIoDAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication Update_2(this global::Ion.IIonApplication builder, global::System.Action<global::Ion.GameTime, global::Counter> step, int order, string? name)
		{
			builder.Schedule.AddFunction(global::Ion.Stage.Update, step, new global::System.Type[] { typeof(global::Counter) }, services => global::Ion.StepAdapters.FromFunction(step, global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Counter>(services)), order, name ?? "App.lambda(Counter)", new global::System.Type[] { typeof(global::Counter) }, global::System.Type.EmptyTypes, "TestApp#2");
			return builder;
		}

		// Program.cs(34,2): Render function Hud.Draw (TestApp#3)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "he2bqA0SwR8+n1kI4VSMqAYEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication Render_3(this global::Ion.IIonApplication builder, global::System.Action<global::Ion.GameTime, global::Counter> step, int order, string? name)
		{
			builder.Schedule.AddFunction(global::Ion.Stage.Render, step, new global::System.Type[] { typeof(global::Counter) }, services => global::Ion.StepAdapters.FromFunction(step, global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Counter>(services)), order, name ?? "Hud.Draw", global::System.Type.EmptyTypes, global::System.Type.EmptyTypes, "TestApp#3");
			return builder;
		}

		// Program.cs(35,67): Last function App.lambda(ILoopContext) (TestApp#4)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "he2bqA0SwR8+n1kI4VSMqGcEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication Last_4(this global::Ion.IIonApplication builder, global::System.Action<global::Ion.GameTime, global::Ion.ILoopContext> step, int order, string? name)
		{
			builder.Schedule.AddFunction(global::Ion.Stage.Last, step, new global::System.Type[] { typeof(global::Ion.ILoopContext) }, services => global::Ion.StepAdapters.FromFunction(step, global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Ion.ILoopContext>(services)), order, name ?? "App.lambda(ILoopContext)", global::System.Type.EmptyTypes, global::System.Type.EmptyTypes, "TestApp#4");
			return builder;
		}

		// Program.cs(36,14): Build: installs the generated schedule the application built at Program.cs:36
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "he2bqA0SwR8+n1kI4VSMqMgEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Core.GameLoop Build_5(this global::Ion.IonApplication receiver)
		{
			receiver.Schedule.UseGenerated(Schedule0Factory.Instance);
			return receiver.Build();
		}
	}

	/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonSystems
	{
		public static readonly global::Ion.GeneratedSystem S0 = new global::Ion.GeneratedSystem(
			typeof(global::Counter),
			typeof(global::Counter),
			"Counter",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, 0, "Tick", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Counter)instance!).Tick),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());
	}

	/// <summary>The schedule of the application built at Program.cs:36: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule0Factory Instance = new Schedule0Factory();

		private Schedule0Factory()
			: base("the application built at Program.cs:36",
				new string[] { "TestApp#0", "TestApp#1", "TestApp#2", "TestApp#3", "TestApp#4" },
				new bool[] { false, false, false, false, true },
				new string[][]
				{
					new string[] { "1|F||0" }, // Init
					global::System.Array.Empty<string>(), // First
					global::System.Array.Empty<string>(), // FixedUpdate
					new string[] { "0|S|Tick|0", "2|F||0" }, // Update
					new string[] { "3|F||0" }, // Render
					new string[] { "4|F||0" }, // Last
					global::System.Array.Empty<string>() // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule0(context);
	}

	/// <summary>The stages of the application built at Program.cs:36 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0 : global::Ion.GeneratedSchedule
	{
		private readonly global::System.Action<global::Ion.GameTime> _f0;
		private readonly global::Counter _s0;
		private readonly global::System.Action<global::Ion.GameTime, global::Counter> _f2;
		private readonly global::Counter _f2_0;
		private readonly global::System.Action<global::Ion.GameTime, global::Counter> _f3;
		private readonly global::Counter _f3_0;
		private readonly bool _g4;
		private readonly global::System.Action<global::Ion.GameTime, global::Ion.ILoopContext> _f4;
		private readonly global::Ion.ILoopContext _f4_0;

		public Schedule0(global::Ion.GeneratedScheduleContext context)
		{
			_f0 = context.Function<global::System.Action<global::Ion.GameTime>>(1);
			_s0 = context.System<global::Counter>(0);
			_f2 = context.Function<global::System.Action<global::Ion.GameTime, global::Counter>>(2);
			_f2_0 = context.Service<global::Counter>(2);
			_f3 = context.Function<global::System.Action<global::Ion.GameTime, global::Counter>>(3);
			_f3_0 = context.Service<global::Counter>(3);
			_g4 = context.IsActive(4);
			_f4 = context.Function<global::System.Action<global::Ion.GameTime, global::Ion.ILoopContext>>(4);
			_f4_0 = context.Service<global::Ion.ILoopContext>(4);
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
			_f0(dt); // 0 App.lambda() (function)
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			_s0.Tick(dt); // 0 Counter.Tick
			_f2(dt, _f2_0); // -1 App.lambda(Counter) (function)
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
			_f3(dt, _f3_0); // 0 Hud.Draw (function)
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
			if (_g4) _f4(dt, _f4_0); // 0 App.lambda(ILoopContext) (function)
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
		}
	}
}
