// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators). Do not edit.
#nullable enable
#pragma warning disable CS0618 // Legacy middleware APIs are intercepted too.

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonInterceptors
	{
		// Program.cs(42,3): UseSystem Wrapper (TestApp#0)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "CjdFCQpCdoazmwrtmvjlOGUEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_0(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S0, "TestApp#0");
			return app;
		}

		// Program.cs(42,3): UseSystem Leaf (TestApp#1)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "CjdFCQpCdoazmwrtmvjlOHoEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_1(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S1, "TestApp#1");
			return app;
		}

		// Program.cs(43,2): Update legacy middleware App.lambda (TestApp#2)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "CjdFCQpCdoazmwrtmvjlOJIEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseUpdate_2(this global::Ion.IonApplication receiver, global::System.Func<global::Ion.GameLoopDelegate, global::Ion.GameLoopDelegate> middleware)
		{
			receiver.Schedule.AddMiddleware(global::Ion.Stage.Update, middleware, 0, "App.lambda", "TestApp#2");
			return receiver;
		}

		// Program.cs(44,2): Last legacy middleware UseDelegateServiceExtensions.lambda (TestApp#3)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "CjdFCQpCdoazmwrtmvjlOAIFAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseLast_3(this global::Ion.IIonApplication app, global::System.Func<global::Ion.GameLoopDelegate, global::Ion.ILoopContext, global::Ion.GameLoopDelegate> middleware)
		{
			app.Schedule.AddMiddleware(global::Ion.Stage.Last, next => middleware(next, global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Ion.ILoopContext>(app.Services)), 0, "UseDelegateServiceExtensions.lambda", "TestApp#3");
			return app;
		}

		// Program.cs(45,14): Build: installs the generated schedule the application built at Program.cs:45
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "CjdFCQpCdoazmwrtmvjlOIMFAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Core.GameLoop Build_4(this global::Ion.IonApplication receiver)
		{
			receiver.Schedule.UseGenerated(Schedule0Factory.Instance);
			return receiver.Build();
		}
	}

	/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonSystems
	{
		public static readonly global::Ion.GeneratedSystem S0 = new global::Ion.GeneratedSystem(
			typeof(global::Wrapper),
			typeof(global::Wrapper),
			"Wrapper",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Middleware, -5, "Around", 0)
				{
					BindMiddleware = static (instance, services) => global::Ion.StepAdapters.FromMiddleware(((global::Wrapper)instance!).Around),
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Middleware, 0, "Factory", 1)
				{
					BindMiddleware = static (instance, services) => new global::System.Func<global::Ion.GameLoopDelegate, global::Ion.GameLoopDelegate>(((global::Wrapper)instance!).Factory),
				}
			},
			new global::Ion.ScheduleDiagnostic[]
			{
				new global::Ion.ScheduleDiagnostic("ION010", global::Ion.ScheduleDiagnosticSeverity.Warning, "'Wrapper.Around' in Update uses the legacy middleware form (GameLoopDelegate next). Rewrite it as a leaf step, [Update] public void Around(GameTime dt), without next(dt); move code that ran after next(dt) into a later step (a higher Order or [After<T>]) or a [Begin]/[End] scope."),
				new global::Ion.ScheduleDiagnostic("ION010", global::Ion.ScheduleDiagnosticSeverity.Warning, "'Wrapper.Factory' in Render uses the legacy middleware form (GameLoopDelegate next). Rewrite it as a leaf step, [Render] public void Factory(GameTime dt), without next(dt); move code that ran after next(dt) into a later step (a higher Order or [After<T>]) or a [Begin]/[End] scope."),
			});

		public static readonly global::Ion.GeneratedSystem S1 = new global::Ion.GeneratedSystem(
			typeof(global::Leaf),
			typeof(global::Leaf),
			"Leaf",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, 0, "Tick", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Leaf)instance!).Tick),
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Step, 0, "Draw", 1)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Leaf)instance!).Draw),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());
	}

	/// <summary>The schedule of the application built at Program.cs:45: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule0Factory Instance = new Schedule0Factory();

		private Schedule0Factory()
			: base("the application built at Program.cs:45",
				new string[] { "TestApp#0", "TestApp#1", "TestApp#2", "TestApp#3" },
				new bool[] { false, false, false, false },
				new string[][]
				{
					global::System.Array.Empty<string>(), // Init
					global::System.Array.Empty<string>(), // First
					global::System.Array.Empty<string>(), // FixedUpdate
					new string[] { "0|M|Around|0", "1|S|Tick|0", "2|D||0" }, // Update
					new string[] { "0|M|Factory|1", "1|S|Draw|1" }, // Render
					new string[] { "3|D||0" }, // Last
					global::System.Array.Empty<string>() // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule0(context);
	}

	/// <summary>The stages of the application built at Program.cs:45 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0 : global::Ion.GeneratedSchedule
	{
		private readonly global::Ion.GameLoopDelegate _next_Update_0;
		private readonly global::Wrapper _s0;
		private readonly global::Ion.GameLoopDelegate _next_Render_1;
		private readonly global::Ion.GameLoopDelegate _m1;
		private readonly global::Ion.GameLoopDelegate _next_Last_2;
		private readonly global::Ion.GameLoopDelegate _m2;
		private readonly global::Leaf _s1;
		private readonly global::Ion.FrameProfiler _prof;
		private readonly global::Ion.SpanId _span0;
		private readonly global::Ion.GameLoopDelegate _next_Update_3;
		private readonly global::Ion.GameLoopDelegate _m4;
		private readonly global::Ion.SpanId _span1;

		public Schedule0(global::Ion.GeneratedScheduleContext context)
		{
			_s0 = context.System<global::Wrapper>(0);
			_s1 = context.System<global::Leaf>(1);
			_prof = context.Profiler;
			_span0 = global::Ion.MetricsIds.Register("Leaf.Tick");
			_span1 = global::Ion.MetricsIds.Register("Leaf.Draw");
			_next_Update_0 = new global::Ion.GameLoopDelegate(Update_0);
			_next_Render_1 = new global::Ion.GameLoopDelegate(Render_1);
			_next_Last_2 = new global::Ion.GameLoopDelegate(Last_2);
			_next_Update_3 = new global::Ion.GameLoopDelegate(Update_3);
			_m4 = context.Middleware(2)(_next_Update_3);
			_m1 = _s0.Factory(_next_Render_1);
			_m2 = context.Middleware(3)(_next_Last_2);
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			// -5 Wrapper.Around (legacy middleware, wraps the rest of the stage)
			_s0.Around(dt, _next_Update_0);
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
			// 0 Wrapper.Factory (legacy middleware, wraps the rest of the stage)
			_m1(dt);
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
			// 0 UseDelegateServiceExtensions.lambda (legacy middleware, wraps the rest of the stage)
			_m2(dt);
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		private void Update_0(global::Ion.GameTime dt)
		{
			{
				long t0 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span0) : 0L;
				_s1.Tick(dt); // 0 Leaf.Tick
				if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span0, t0);
			}
			// 0 App.lambda (legacy middleware, wraps the rest of the stage)
			_m4(dt);
		}

		[global::System.Diagnostics.StackTraceHidden]
		private void Render_1(global::Ion.GameTime dt)
		{
			{
				long t1 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span1) : 0L;
				_s1.Draw(dt); // 0 Leaf.Draw
				if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span1, t1);
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		private void Last_2(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		private void Update_3(global::Ion.GameTime dt)
		{
		}
	}
}
