// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators). Do not edit.
#nullable enable
#pragma warning disable CS0618 // Legacy middleware APIs are intercepted too.

[assembly: global::Ion.ScheduleRegistrationsAttribute("M:Plugin.PluginExtensions.UsePlugin(Ion.IIonApplication,System.Boolean)#0", "S|Plugin#0|0|0|0\nS|Plugin#1|1|1|1", typeof(global::Plugin.PluginSystem), typeof(global::Plugin.HiddenSystem))]

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonInterceptors
	{
		// Program.cs(22,3): UseSystem PluginSystem (Plugin#0)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "HT5fNCQ6A9VhnNasl7a5Qx0CAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_0(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S0, "Plugin#0");
			return app;
		}

		// Program.cs(23,19): UseSystem HiddenSystem (Plugin#1)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "HT5fNCQ6A9VhnNasl7a5Q04CAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_1(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S1, "Plugin#1");
			return app;
		}
	}

	/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonSystems
	{
		public static readonly global::Ion.GeneratedSystem S0 = new global::Ion.GeneratedSystem(
			typeof(global::Plugin.PluginSystem),
			typeof(global::Plugin.PluginSystem),
			"PluginSystem",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, -100, "Tick", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Plugin.PluginSystem)instance!).Tick),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		public static readonly global::Ion.GeneratedSystem S1 = new global::Ion.GeneratedSystem(
			typeof(global::Plugin.HiddenSystem),
			typeof(global::Plugin.HiddenSystem),
			"HiddenSystem",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Step, 0, "Draw", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Plugin.HiddenSystem)instance!).Draw),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());
	}
}
