// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators). Do not edit.
#nullable enable
#pragma warning disable CS0618 // Legacy middleware APIs are intercepted too.

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonInterceptors
	{
		// Program.cs(27,3): UseSystem Game (PluginApp#0)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "FTGvLUyzCZQ+HM0JKXyuLUgCAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_0(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S0, "PluginApp#0");
			return app;
		}

		// Program.cs(28,3): Run: installs the generated schedule the application built at Program.cs:28
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "FTGvLUyzCZQ+HM0JKXyuLWECAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static void Run_1(this global::Ion.IonApplication receiver)
		{
			receiver.Schedule.UseGenerated(Schedule0Factory.Instance);
			receiver.Run();
		}
	}

	/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonSystems
	{
		public static readonly global::Ion.GeneratedSystem S0 = new global::Ion.GeneratedSystem(
			typeof(global::Game),
			typeof(global::Game),
			"Game",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, 0, "Tick", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Game)instance!).Tick),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());
	}

	/// <summary>The schedule of the application built at Program.cs:28: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule0Factory Instance = new Schedule0Factory();

		private Schedule0Factory()
			: base("the application built at Program.cs:28",
				new string[] { "Plugin#0", "Plugin#1", "PluginApp#0" },
				new bool[] { false, true, false },
				new string[][]
				{
					global::System.Array.Empty<string>(), // Init
					global::System.Array.Empty<string>(), // First
					global::System.Array.Empty<string>(), // FixedUpdate
					new string[] { "0|S|Tick|0", "2|S|Tick|0" }, // Update
					new string[] { "1|S|Draw|0" }, // Render
					global::System.Array.Empty<string>(), // Last
					global::System.Array.Empty<string>() // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule0(context);
	}

	/// <summary>The stages of the application built at Program.cs:28 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0 : global::Ion.GeneratedSchedule
	{
		private readonly global::Plugin.PluginSystem _s0;
		private readonly global::Game _s2;
		private readonly bool _g1;
		private readonly global::Ion.GameLoopDelegate _d2;

		public Schedule0(global::Ion.GeneratedScheduleContext context)
		{
			_s0 = context.System<global::Plugin.PluginSystem>(0);
			_s2 = context.System<global::Game>(2);
			_g1 = context.IsActive(1);
			_d2 = context.Step(1, global::Ion.Stage.Render, "Draw", 0);
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			_s0.Tick(dt); // -100 PluginSystem.Tick
			_s2.Tick(dt); // 0 Game.Tick
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
			if (_g1) _d2(dt); // 0 HiddenSystem.Draw
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
		}
	}
}
