// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators). Do not edit.
#nullable enable
#pragma warning disable CS0618 // Legacy middleware APIs are intercepted too.

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonInterceptors
	{
		// Program.cs(36,3): UseSystem Sprites (TestApp#0)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "tBqtAgL0whQyfixqIGvdUmoEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_0(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S0, "TestApp#0");
			return app;
		}

		// Program.cs(36,3): UseSystem Frame (TestApp#1)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "tBqtAgL0whQyfixqIGvdUn8EAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_1(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S1, "TestApp#1");
			return app;
		}

		// Program.cs(37,14): Build: installs the generated schedule the application built at Program.cs:37
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "tBqtAgL0whQyfixqIGvdUqQEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Core.GameLoop Build_2(this global::Ion.IonApplication receiver)
		{
			receiver.Schedule.UseGenerated(Schedule0Factory.Instance);
			return receiver.Build();
		}
	}

	/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonSystems
	{
		public static readonly global::Ion.GeneratedSystem S0 = new global::Ion.GeneratedSystem(
			typeof(global::Sprites),
			typeof(global::Sprites),
			"Sprites",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Step, 0, "Draw", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Sprites)instance!).Draw),
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, 0, "Tick", 1)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Sprites)instance!).Tick),
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, 5, "Late", 2)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Sprites)instance!).Late),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		public static readonly global::Ion.GeneratedSystem S1 = new global::Ion.GeneratedSystem(
			typeof(global::Frame),
			typeof(global::Frame),
			"Frame",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Scope, -900, "Begin", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Frame)instance!).Begin),
					EndMethod = "End",
					BindEnd = static (instance, services) => global::Ion.StepAdapters.FromAction(((global::Frame)instance!).End),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());
	}

	/// <summary>The schedule of the application built at Program.cs:37: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule0Factory Instance = new Schedule0Factory();

		private Schedule0Factory()
			: base("the application built at Program.cs:37",
				new string[] { "TestApp#0", "TestApp#1" },
				new bool[] { false, false },
				new string[][]
				{
					global::System.Array.Empty<string>(), // Init
					global::System.Array.Empty<string>(), // First
					global::System.Array.Empty<string>(), // FixedUpdate
					new string[] { "0|S|Tick|1", "0|S|Late|2" }, // Update
					new string[] { "1|B|Begin|0", "0|S|Draw|0" }, // Render
					global::System.Array.Empty<string>(), // Last
					global::System.Array.Empty<string>() // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule0(context);
	}

	/// <summary>The stages of the application built at Program.cs:37 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0 : global::Ion.GeneratedSchedule
	{
		private readonly global::Ion.FrameProfiler _prof;
		private readonly global::Sprites _s0;
		private readonly global::Ion.SpanId _span0;
		private readonly global::Ion.SpanId _span1;
		private readonly global::Frame _s1;
		private readonly global::Ion.SpanId _span2;
		private readonly global::Ion.SpanId _span3;

		public Schedule0(global::Ion.GeneratedScheduleContext context)
		{
			_prof = context.Profiler;
			_s0 = context.System<global::Sprites>(0);
			_span0 = global::Ion.MetricsIds.Register("Sprites.Tick");
			_span1 = global::Ion.MetricsIds.Register("Sprites.Late");
			_s1 = context.System<global::Frame>(1);
			_span2 = global::Ion.MetricsIds.Register("Frame.Begin");
			_span3 = global::Ion.MetricsIds.Register("Sprites.Draw");
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t0 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span0) : 0L;
					_s0.Tick(dt); // 0 Sprites.Tick
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span0, t0);
				}
				{
					long t1 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span1) : 0L;
					_s0.Late(dt); // 5 Sprites.Late
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span1, t1);
				}
			}
			else
			{
				_s0.Tick(dt); // 0 Sprites.Tick
				_s0.Late(dt); // 5 Sprites.Late
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				// -900 Frame.Begin ... Frame.End
				long t2 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span2) : 0L;
				_s1.Begin(dt);
				try
				{
					{
						long t3 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span3) : 0L;
						_s0.Draw(dt); // 0 Sprites.Draw
						if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span3, t3);
					}
				}
				finally
				{
					_s1.End();
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span2, t2);
				}
			}
			else
			{
				// -900 Frame.Begin ... Frame.End
				_s1.Begin(dt);
				try
				{
					_s0.Draw(dt); // 0 Sprites.Draw
				}
				finally
				{
					_s1.End();
				}
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
		}
	}
}
