// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators). Do not edit.
#nullable enable
#pragma warning disable CS0618 // Legacy middleware APIs are intercepted too.

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonInterceptors
	{
		// Program.cs(45,3): UseSystem Movement (QueryApp#0)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "kO0uijQeqv/21Q870JGGq7IFAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_0(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S0, "QueryApp#0");
			return app;
		}

		// Program.cs(46,14): Build: installs the generated schedule the application built at Program.cs:46
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "kO0uijQeqv/21Q870JGGq9oFAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Core.GameLoop Build_1(this global::Ion.IonApplication receiver)
		{
			receiver.Schedule.UseGenerated(Schedule0Factory.Instance);
			return receiver.Build();
		}
	}

	/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonSystems
	{
		public static readonly global::Ion.GeneratedSystem S0 = new global::Ion.GeneratedSystem(
			typeof(global::Movement),
			typeof(global::Movement),
			"Movement",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Step, 0, "Draw", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Movement)instance!).Draw),
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, 0, "Move", 1)
				{
					Services = new global::System.Type[] { typeof(global::Arch.Core.World) },
					Bind = static (instance, services) => new S0_Move_Query0((global::Movement)instance!, services).Invoke,
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, 5, "Damage", 2)
				{
					Services = new global::System.Type[] { typeof(global::Arch.Core.World), typeof(global::Ion.Extensions.Ecs.Commands) },
					Bind = static (instance, services) => new S0_Damage_Query1((global::Movement)instance!, services).Invoke,
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Last, global::Ion.GeneratedStepKind.Step, 7, "Report", 3)
				{
					IsStatic = true,
					Services = new global::System.Type[] { typeof(global::Arch.Core.World) },
					Bind = static (instance, services) => new S0_Report_Query2(services).Invoke,
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
		[global::System.Diagnostics.DebuggerNonUserCode]
		[global::System.Diagnostics.StackTraceHidden]
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		private sealed class S0_Move_Query0
		{
			private readonly global::Movement _system;
			private readonly global::Arch.Core.World _world;

			public S0_Move_Query0(global::Movement system, global::System.IServiceProvider services)
			{
				_system = system;
				_world = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Arch.Core.World>(services);
			}

			[global::System.Diagnostics.StackTraceHidden]
			public void Invoke(global::Ion.GameTime dt) => _system.__IonQuery_Move(dt, _world);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
		[global::System.Diagnostics.DebuggerNonUserCode]
		[global::System.Diagnostics.StackTraceHidden]
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		private sealed class S0_Damage_Query1
		{
			private readonly global::Movement _system;
			private readonly global::Arch.Core.World _world;
			private readonly global::Ion.Extensions.Ecs.Commands _commands;

			public S0_Damage_Query1(global::Movement system, global::System.IServiceProvider services)
			{
				_system = system;
				_world = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Arch.Core.World>(services);
				_commands = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Ion.Extensions.Ecs.Commands>(services);
			}

			[global::System.Diagnostics.StackTraceHidden]
			public void Invoke(global::Ion.GameTime dt) => _system.__IonQuery_Damage(dt, _world, _commands);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
		[global::System.Diagnostics.DebuggerNonUserCode]
		[global::System.Diagnostics.StackTraceHidden]
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		private sealed class S0_Report_Query2
		{
			private readonly global::Arch.Core.World _world;

			public S0_Report_Query2(global::System.IServiceProvider services)
			{
				_world = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Arch.Core.World>(services);
			}

			[global::System.Diagnostics.StackTraceHidden]
			public void Invoke(global::Ion.GameTime dt) => global::Movement.__IonQuery_Report(dt, _world);
		}
	}

	/// <summary>The schedule of the application built at Program.cs:46: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule0Factory Instance = new Schedule0Factory();

		private Schedule0Factory()
			: base("the application built at Program.cs:46",
				new string[] { "Ion.Extensions.Ecs#0", "Ion.Extensions.Ecs#1", "Ion.Extensions.Ecs#2", "QueryApp#0" },
				new bool[] { false, false, false, false },
				new string[][]
				{
					new string[] { "0|S|FlushInit|0" }, // Init
					new string[] { "0|S|FlushFirst|1" }, // First
					new string[] { "0|S|FlushFixedUpdate|2" }, // FixedUpdate
					new string[] { "3|S|Move|1", "3|S|Damage|2", "2|S|Animate|0", "0|S|FlushUpdate|3" }, // Update
					new string[] { "1|S|PropagateBeforeRender|1", "3|S|Draw|0", "0|S|FlushRender|4" }, // Render
					new string[] { "1|S|PropagateLast|0", "3|S|Report|3", "0|S|FlushLast|5" }, // Last
					new string[] { "0|S|FlushDestroy|6" } // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule0(context);
	}

	/// <summary>The stages of the application built at Program.cs:46 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0 : global::Ion.GeneratedSchedule
	{
		private readonly global::Ion.FrameProfiler _prof;
		private readonly global::Ion.Extensions.Ecs.EcsCommandsSystem _s0;
		private readonly global::Ion.SpanId _span0;
		private readonly global::Ion.SpanId _span1;
		private readonly global::Ion.SpanId _span2;
		private readonly global::Arch.Core.World _p3_0;
		private readonly global::Movement _s3;
		private readonly global::Ion.SpanId _span3;
		private readonly global::Arch.Core.World _p4_0;
		private readonly global::Ion.Extensions.Ecs.Commands _p4_1;
		private readonly global::Ion.SpanId _span4;
		private readonly global::Arch.Core.World _p6_0;
		private readonly global::Ion.SpanId _span5;
		private readonly global::Ion.SpanId _span6;
		private readonly global::Ion.Extensions.Ecs.TransformPropagationSystem _s1;
		private readonly global::Ion.SpanId _span7;
		private readonly global::Ion.SpanId _span8;
		private readonly global::Ion.SpanId _span9;
		private readonly global::Ion.SpanId _span10;
		private readonly global::Arch.Core.World _p11_0;
		private readonly global::Ion.SpanId _span11;
		private readonly global::Ion.SpanId _span12;
		private readonly global::Ion.SpanId _span13;

		public Schedule0(global::Ion.GeneratedScheduleContext context)
		{
			_prof = context.Profiler;
			_s0 = context.System<global::Ion.Extensions.Ecs.EcsCommandsSystem>(0);
			_span0 = global::Ion.MetricsIds.Register("EcsCommandsSystem.FlushInit");
			_span1 = global::Ion.MetricsIds.Register("EcsCommandsSystem.FlushFirst");
			_span2 = global::Ion.MetricsIds.Register("EcsCommandsSystem.FlushFixedUpdate");
			_p3_0 = context.Service<global::Arch.Core.World>(3);
			_s3 = context.System<global::Movement>(3);
			_span3 = global::Ion.MetricsIds.Register("Movement.Move");
			_p4_0 = context.Service<global::Arch.Core.World>(3);
			_p4_1 = context.Service<global::Ion.Extensions.Ecs.Commands>(3);
			_span4 = global::Ion.MetricsIds.Register("Movement.Damage");
			_p6_0 = context.Service<global::Arch.Core.World>(2);
			_span5 = global::Ion.MetricsIds.Register("SpriteAnimationSystem.Animate");
			_span6 = global::Ion.MetricsIds.Register("EcsCommandsSystem.FlushUpdate");
			_s1 = context.System<global::Ion.Extensions.Ecs.TransformPropagationSystem>(1);
			_span7 = global::Ion.MetricsIds.Register("TransformPropagationSystem.PropagateBeforeRender");
			_span8 = global::Ion.MetricsIds.Register("Movement.Draw");
			_span9 = global::Ion.MetricsIds.Register("EcsCommandsSystem.FlushRender");
			_span10 = global::Ion.MetricsIds.Register("TransformPropagationSystem.PropagateLast");
			_p11_0 = context.Service<global::Arch.Core.World>(3);
			_span11 = global::Ion.MetricsIds.Register("Movement.Report");
			_span12 = global::Ion.MetricsIds.Register("EcsCommandsSystem.FlushLast");
			_span13 = global::Ion.MetricsIds.Register("EcsCommandsSystem.FlushDestroy");
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t0 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span0) : 0L;
					_s0.FlushInit(dt); // 950 EcsCommandsSystem.FlushInit
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span0, t0);
				}
			}
			else
			{
				_s0.FlushInit(dt); // 950 EcsCommandsSystem.FlushInit
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t1 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span1) : 0L;
					_s0.FlushFirst(dt); // 950 EcsCommandsSystem.FlushFirst
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span1, t1);
				}
			}
			else
			{
				_s0.FlushFirst(dt); // 950 EcsCommandsSystem.FlushFirst
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t2 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span2) : 0L;
					_s0.FlushFixedUpdate(dt); // 950 EcsCommandsSystem.FlushFixedUpdate
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span2, t2);
				}
			}
			else
			{
				_s0.FlushFixedUpdate(dt); // 950 EcsCommandsSystem.FlushFixedUpdate
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t3 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span3) : 0L;
					_s3.__IonQuery_Move(dt, _p3_0); // 0 Movement.Move
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span3, t3);
				}
				{
					long t4 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span4) : 0L;
					_s3.__IonQuery_Damage(dt, _p4_0, _p4_1); // 5 Movement.Damage
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span4, t4);
				}
				{
					long t5 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span5) : 0L;
					global::Ion.Extensions.Ecs.SpriteAnimationSystem.__IonQuery_Animate(dt, _p6_0); // 400 SpriteAnimationSystem.Animate
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span5, t5);
				}
				{
					long t6 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span6) : 0L;
					_s0.FlushUpdate(dt); // 950 EcsCommandsSystem.FlushUpdate
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span6, t6);
				}
			}
			else
			{
				_s3.__IonQuery_Move(dt, _p3_0); // 0 Movement.Move
				_s3.__IonQuery_Damage(dt, _p4_0, _p4_1); // 5 Movement.Damage
				global::Ion.Extensions.Ecs.SpriteAnimationSystem.__IonQuery_Animate(dt, _p6_0); // 400 SpriteAnimationSystem.Animate
				_s0.FlushUpdate(dt); // 950 EcsCommandsSystem.FlushUpdate
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t7 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span7) : 0L;
					_s1.PropagateBeforeRender(dt); // -400 TransformPropagationSystem.PropagateBeforeRender
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span7, t7);
				}
				{
					long t8 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span8) : 0L;
					_s3.Draw(dt); // 0 Movement.Draw
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span8, t8);
				}
				{
					long t9 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span9) : 0L;
					_s0.FlushRender(dt); // 950 EcsCommandsSystem.FlushRender
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span9, t9);
				}
			}
			else
			{
				_s1.PropagateBeforeRender(dt); // -400 TransformPropagationSystem.PropagateBeforeRender
				_s3.Draw(dt); // 0 Movement.Draw
				_s0.FlushRender(dt); // 950 EcsCommandsSystem.FlushRender
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t10 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span10) : 0L;
					_s1.PropagateLast(dt); // -400 TransformPropagationSystem.PropagateLast
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span10, t10);
				}
				{
					long t11 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span11) : 0L;
					global::Movement.__IonQuery_Report(dt, _p11_0); // 7 Movement.Report
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span11, t11);
				}
				{
					long t12 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span12) : 0L;
					_s0.FlushLast(dt); // 950 EcsCommandsSystem.FlushLast
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span12, t12);
				}
			}
			else
			{
				_s1.PropagateLast(dt); // -400 TransformPropagationSystem.PropagateLast
				global::Movement.__IonQuery_Report(dt, _p11_0); // 7 Movement.Report
				_s0.FlushLast(dt); // 950 EcsCommandsSystem.FlushLast
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t13 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span13) : 0L;
					_s0.FlushDestroy(dt); // 950 EcsCommandsSystem.FlushDestroy
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span13, t13);
				}
			}
			else
			{
				_s0.FlushDestroy(dt); // 950 EcsCommandsSystem.FlushDestroy
			}
		}
	}
}
