// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators): [Query] methods expanded into chunk loops. Do not edit.
#nullable enable
#pragma warning disable CS0618, CS1591, CA2255

partial class Movement
{
	private static readonly global::Arch.Core.QueryDescription __IonQuery_Move_Description = new global::Arch.Core.QueryDescription(
		all: new global::Arch.Core.Signature(global::Arch.Core.Component<global::Ion.Extensions.Ecs.Transform2D>.ComponentType, global::Arch.Core.Component<global::Velocity>.ComponentType),
		any: null,
		none: new global::Arch.Core.Signature(global::Arch.Core.Component<global::Frozen>.ComponentType));

	/// <summary>Runs <see cref="Move"/> for every matching entity of <paramref name="world"/> (generated from its [Query]).</summary>
	[global::Ion.ExpandedStep("Move")]
	[global::Ion.UpdateAttribute]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	public void __IonQuery_Move(global::Ion.GameTime dt, global::Arch.Core.World world)
	{
		var __delta = dt.Delta;
		foreach (ref var __chunk in world.Query(in __IonQuery_Move_Description))
		{
			var __count = __chunk.Count;
			var __size = world.Size;
			ref var __entities = ref __chunk.Entity(0);
			ref var __c0 = ref __chunk.GetFirst<global::Ion.Extensions.Ecs.Transform2D>();
			ref var __c1 = ref __chunk.GetFirst<global::Velocity>();
			for (var __i = __count - 1; __i >= 0; __i--)
			{
				var __entity = global::System.Runtime.CompilerServices.Unsafe.Add(ref __entities, __i);
				Move(ref global::System.Runtime.CompilerServices.Unsafe.Add(ref __c0, __i), in global::System.Runtime.CompilerServices.Unsafe.Add(ref __c1, __i), in __delta);
				if (__chunk.Count != __count || world.Size != __size) global::Ion.Extensions.Ecs.QueryGuard.ThrowStructuralChange("Movement.Move", __entity);
			}
		}
	}

	private static readonly global::Arch.Core.QueryDescription __IonQuery_Damage_Description = new global::Arch.Core.QueryDescription(
		all: new global::Arch.Core.Signature(global::Arch.Core.Component<global::Health>.ComponentType),
		any: null,
		none: null);

	/// <summary>Runs <see cref="Damage"/> for every matching entity of <paramref name="world"/> (generated from its [Query]).</summary>
	[global::Ion.ExpandedStep("Damage")]
	[global::Ion.UpdateAttribute(Order = 5)]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	public void __IonQuery_Damage(global::Ion.GameTime dt, global::Arch.Core.World world, global::Ion.Extensions.Ecs.Commands commands)
	{
		foreach (ref var __chunk in world.Query(in __IonQuery_Damage_Description))
		{
			var __count = __chunk.Count;
			var __size = world.Size;
			ref var __entities = ref __chunk.Entity(0);
			ref var __c0 = ref __chunk.GetFirst<global::Health>();
			for (var __i = __count - 1; __i >= 0; __i--)
			{
				var __entity = global::System.Runtime.CompilerServices.Unsafe.Add(ref __entities, __i);
				Damage(__entity, ref global::System.Runtime.CompilerServices.Unsafe.Add(ref __c0, __i), commands);
				if (__chunk.Count != __count || world.Size != __size) global::Ion.Extensions.Ecs.QueryGuard.ThrowStructuralChange("Movement.Damage", __entity);
			}
		}
	}

	private static readonly global::Arch.Core.QueryDescription __IonQuery_Report_Description = new global::Arch.Core.QueryDescription(
		all: new global::Arch.Core.Signature(global::Arch.Core.Component<global::Ion.Extensions.Ecs.Transform2D>.ComponentType, global::Arch.Core.Component<global::Velocity>.ComponentType),
		any: new global::Arch.Core.Signature(global::Arch.Core.Component<global::Frozen>.ComponentType, global::Arch.Core.Component<global::Ion.Extensions.Ecs.Transform2D>.ComponentType),
		none: null);

	/// <summary>Runs <see cref="Report"/> for every matching entity of <paramref name="world"/> (generated from its [Query]).</summary>
	[global::Ion.ExpandedStep("Report")]
	[global::Ion.LastAttribute(Order = 7)]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	public static void __IonQuery_Report(global::Ion.GameTime dt, global::Arch.Core.World world)
	{
		foreach (ref var __chunk in world.Query(in __IonQuery_Report_Description))
		{
			var __count = __chunk.Count;
			var __size = world.Size;
			ref var __entities = ref __chunk.Entity(0);
			ref var __c0 = ref __chunk.GetFirst<global::Ion.Extensions.Ecs.Transform2D>();
			for (var __i = __count - 1; __i >= 0; __i--)
			{
				var __entity = global::System.Runtime.CompilerServices.Unsafe.Add(ref __entities, __i);
				Report(in global::System.Runtime.CompilerServices.Unsafe.Add(ref __c0, __i), dt, world);
				if (__chunk.Count != __count || world.Size != __size) global::Ion.Extensions.Ecs.QueryGuard.ThrowStructuralChange("Movement.Report", __entity);
			}
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Registers the components of this assembly's [Query] methods with Arch (NativeAOT needs their arrays up front).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonQueryComponents
	{
		[global::System.Runtime.CompilerServices.ModuleInitializer]
		internal static void Register()
		{
			global::Ion.Extensions.Ecs.EcsComponents.Register<global::Ion.Extensions.Ecs.Transform2D>();
			global::Ion.Extensions.Ecs.EcsComponents.Register<global::Velocity>();
			global::Ion.Extensions.Ecs.EcsComponents.Register<global::Frozen>();
			global::Ion.Extensions.Ecs.EcsComponents.Register<global::Health>();
		}
	}
}
