// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators). Do not edit.
#nullable enable
#pragma warning disable CS0618 // Obsolete systems are registered too.

[assembly: global::Ion.ScheduleRegistrationsAttribute("M:Modules.UseRenderer(Ion.IIonApplication)#0", "S|TestApp#0|0|0|0\nS|TestApp#1|0|1|1", typeof(global::Input), typeof(global::Renderer))]
[assembly: global::Ion.ScheduleRegistrationsAttribute("M:Modules.UseExtraction(Ion.IIonApplication)#0", "S|TestApp#0|0|0|0\nS|TestApp#1|0|1|1\nS|TestApp#2|0|2|2", typeof(global::Input), typeof(global::Renderer), typeof(global::Extraction))]

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonInterceptors
	{
		// Program.cs(21,73): UseSystem Input (TestApp#0)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WYYDAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_0(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S0, "TestApp#0");
			return app;
		}

		// Program.cs(21,73): UseSystem Renderer (TestApp#1)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WZkDAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_1(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S1, "TestApp#1");
			return app;
		}

		// Program.cs(22,75): UseSystem Extraction (TestApp#2)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WQwEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_2(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S2, "TestApp#2");
			return app;
		}

		// Program.cs(32,3): UseSystem Input (TestApp#3)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WeUFAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_3(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S0, "TestApp#3");
			return app;
		}

		// Program.cs(33,71): UseSystem Late (TestApp#4)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WUMGAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_4(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S3, "TestApp#4");
			return app;
		}

		// Program.cs(34,27): UseSystem Menu (TestApp#5)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WXYGAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Extensions.Scenes.ISceneBuilder UseSystem_5(this global::Ion.Extensions.Scenes.ISceneBuilder scene)
		{
			global::System.ArgumentNullException.ThrowIfNull(scene);
			scene.Schedule.AddSystem(IonSystems.S4, "TestApp#5");
			return scene;
		}

		// Program.cs(34,27): UseSystem Menu (TestApp#6)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WYgGAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Extensions.Scenes.ISceneBuilder UseSystem_6(this global::Ion.Extensions.Scenes.ISceneBuilder scene)
		{
			global::System.ArgumentNullException.ThrowIfNull(scene);
			scene.Schedule.AddSystem(IonSystems.S4, "TestApp#6");
			return scene;
		}

		// Program.cs(34,2): UseScene Scene 1
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WVsGAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseScene_7(this global::Ion.IIonApplication app, int sceneId, global::System.Action<global::Ion.Extensions.Scenes.ISceneBuilder> configure)
		{
			return global::Ion.Extensions.Scenes.BuilderExtensions.UseScene(app, sceneId, configure, Schedule0Factory.Instance);
		}

		// Program.cs(35,2): UseSystem Extraction (TestApp#8)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WaEGAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_8(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S2, "TestApp#8");
			return app;
		}

		// Program.cs(35,2): UseSystem Late (TestApp#9)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WbkGAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_9(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S3, "TestApp#9");
			return app;
		}

		// Program.cs(37,14): Build: installs the generated schedule the application built at Program.cs:37
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "b/jrOpPhueWgawhc2lD3WR0HAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Core.GameLoop Build_10(this global::Ion.IonApplication receiver)
		{
			receiver.Schedule.UseGenerated(Schedule1Factory.Instance);
			return receiver.Build();
		}
	}

	/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonSystems
	{
		public static readonly global::Ion.GeneratedSystem S0 = new global::Ion.GeneratedSystem(
			typeof(global::Input),
			typeof(global::Input),
			"Input",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.First, global::Ion.GeneratedStepKind.Step, 0, "Poll", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Input)instance!).Poll),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		public static readonly global::Ion.GeneratedSystem S1 = new global::Ion.GeneratedSystem(
			typeof(global::Renderer),
			typeof(global::Renderer),
			"Renderer",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Step, -10, "Draw", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Renderer)instance!).Draw),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		public static readonly global::Ion.GeneratedSystem S2 = new global::Ion.GeneratedSystem(
			typeof(global::Extraction),
			typeof(global::Extraction),
			"Extraction",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Step, 0, "Extract", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Extraction)instance!).Extract),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		public static readonly global::Ion.GeneratedSystem S3 = new global::Ion.GeneratedSystem(
			typeof(global::Late),
			typeof(global::Late),
			"Late",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Last, global::Ion.GeneratedStepKind.Step, 0, "Finish", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Late)instance!).Finish),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		public static readonly global::Ion.GeneratedSystem S4 = new global::Ion.GeneratedSystem(
			typeof(global::Menu),
			typeof(global::Menu),
			"Menu",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, 0, "Tick", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Menu)instance!).Tick),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());
	}

	/// <summary>The schedule of Scene 1 registered at Program.cs:34: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule0Factory Instance = new Schedule0Factory();

		private Schedule0Factory()
			: base("Scene 1 registered at Program.cs:34",
				new string[] { "TestApp#5" },
				new bool[] { false },
				new string[][]
				{
					global::System.Array.Empty<string>(), // Init
					global::System.Array.Empty<string>(), // First
					global::System.Array.Empty<string>(), // FixedUpdate
					new string[] { "0|S|Tick|0" }, // Update
					global::System.Array.Empty<string>(), // Render
					global::System.Array.Empty<string>(), // Last
					global::System.Array.Empty<string>() // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule0(context);
	}

	/// <summary>The stages of Scene 1 registered at Program.cs:34 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0 : global::Ion.GeneratedSchedule
	{
		private readonly global::Ion.FrameProfiler _prof;
		private readonly global::Menu _s0;
		private readonly global::Ion.SpanId _span0;

		public Schedule0(global::Ion.GeneratedScheduleContext context)
		{
			_prof = context.Profiler;
			_s0 = context.System<global::Menu>(0);
			_span0 = global::Ion.MetricsIds.Register("Menu.Tick");
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t0 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span0) : 0L;
					_s0.Tick(dt); // 0 Menu.Tick
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span0, t0);
				}
			}
			else
			{
				_s0.Tick(dt); // 0 Menu.Tick
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
		}
	}

	/// <summary>The schedule of the application built at Program.cs:37: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule1Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule1Factory Instance = new Schedule1Factory();

		private Schedule1Factory()
			: base("the application built at Program.cs:37",
				new string[] { "Ion.Core#0", "TestApp#0", "TestApp#1", "TestApp#2", "TestApp#4", "Ion.Extensions.Scenes#0", "TestApp#9" },
				new bool[] { false, false, false, false, true, true, true },
				new string[][]
				{
					new string[] { "5|S|Init|0" }, // Init
					new string[] { "5|S|First|1", "1|S|Poll|0" }, // First
					new string[] { "5|S|FixedUpdate|2" }, // FixedUpdate
					new string[] { "5|S|Update|3" }, // Update
					new string[] { "5|S|Render|4", "2|S|Draw|0", "3|S|Extract|0" }, // Render
					new string[] { "5|S|Last|5", "4|S|Finish|0", "6|S|Finish|0", "0|S|StepEvents|0" }, // Last
					new string[] { "5|S|Destroy|6" } // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule1(context);
	}

	/// <summary>The stages of the application built at Program.cs:37 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule1 : global::Ion.GeneratedSchedule
	{
		private readonly global::Ion.FrameProfiler _prof;
		private readonly bool _g5;
		private readonly global::Ion.Extensions.Scenes.SceneSystem _s5;
		private readonly global::Ion.SpanId _span0;
		private readonly global::Ion.SpanId _span1;
		private readonly global::Input _s1;
		private readonly global::Ion.SpanId _span2;
		private readonly global::Ion.SpanId _span3;
		private readonly global::Ion.SpanId _span4;
		private readonly global::Ion.SpanId _span5;
		private readonly global::Renderer _s2;
		private readonly global::Ion.SpanId _span6;
		private readonly global::Extraction _s3;
		private readonly global::Ion.SpanId _span7;
		private readonly global::Ion.SpanId _span8;
		private readonly bool _g4;
		private readonly global::Late _s4;
		private readonly global::Ion.SpanId _span9;
		private readonly bool _g6;
		private readonly global::Late _s6;
		private readonly global::Ion.SpanId _span10;
		private readonly global::Ion.GameLoopDelegate _d11;
		private readonly global::Ion.SpanId _span11;
		private readonly global::Ion.SpanId _span12;

		public Schedule1(global::Ion.GeneratedScheduleContext context)
		{
			_prof = context.Profiler;
			_g5 = context.IsActive(5);
			_s5 = context.System<global::Ion.Extensions.Scenes.SceneSystem>(5);
			_span0 = global::Ion.MetricsIds.Register("SceneSystem.Init");
			_span1 = global::Ion.MetricsIds.Register("SceneSystem.First");
			_s1 = context.System<global::Input>(1);
			_span2 = global::Ion.MetricsIds.Register("Input.Poll");
			_span3 = global::Ion.MetricsIds.Register("SceneSystem.FixedUpdate");
			_span4 = global::Ion.MetricsIds.Register("SceneSystem.Update");
			_span5 = global::Ion.MetricsIds.Register("SceneSystem.Render");
			_s2 = context.System<global::Renderer>(2);
			_span6 = global::Ion.MetricsIds.Register("Renderer.Draw");
			_s3 = context.System<global::Extraction>(3);
			_span7 = global::Ion.MetricsIds.Register("Extraction.Extract");
			_span8 = global::Ion.MetricsIds.Register("SceneSystem.Last");
			_g4 = context.IsActive(4);
			_s4 = context.System<global::Late>(4);
			_span9 = global::Ion.MetricsIds.Register("Late.Finish");
			_g6 = context.IsActive(6);
			_s6 = context.System<global::Late>(6);
			_span10 = global::Ion.MetricsIds.Register("Late.Finish");
			_d11 = context.Step(0, global::Ion.Stage.Last, "StepEvents", 0);
			_span11 = global::Ion.MetricsIds.Register("EventSystem.StepEvents");
			_span12 = global::Ion.MetricsIds.Register("SceneSystem.Destroy");
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				if (_g5)
				{
					long t0 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span0) : 0L;
					_s5.Init(dt); // -500 SceneSystem.Init
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span0, t0);
				}
			}
			else
			{
				if (_g5) _s5.Init(dt); // -500 SceneSystem.Init
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				if (_g5)
				{
					long t1 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span1) : 0L;
					_s5.First(dt); // -500 SceneSystem.First
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span1, t1);
				}
				{
					long t2 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span2) : 0L;
					_s1.Poll(dt); // 0 Input.Poll
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span2, t2);
				}
			}
			else
			{
				if (_g5) _s5.First(dt); // -500 SceneSystem.First
				_s1.Poll(dt); // 0 Input.Poll
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				if (_g5)
				{
					long t3 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span3) : 0L;
					_s5.FixedUpdate(dt); // -500 SceneSystem.FixedUpdate
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span3, t3);
				}
			}
			else
			{
				if (_g5) _s5.FixedUpdate(dt); // -500 SceneSystem.FixedUpdate
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				if (_g5)
				{
					long t4 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span4) : 0L;
					_s5.Update(dt); // -500 SceneSystem.Update
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span4, t4);
				}
			}
			else
			{
				if (_g5) _s5.Update(dt); // -500 SceneSystem.Update
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				if (_g5)
				{
					long t5 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span5) : 0L;
					_s5.Render(dt); // -500 SceneSystem.Render
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span5, t5);
				}
				{
					long t6 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span6) : 0L;
					_s2.Draw(dt); // -10 Renderer.Draw
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span6, t6);
				}
				{
					long t7 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span7) : 0L;
					_s3.Extract(dt); // 0 Extraction.Extract
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span7, t7);
				}
			}
			else
			{
				if (_g5) _s5.Render(dt); // -500 SceneSystem.Render
				_s2.Draw(dt); // -10 Renderer.Draw
				_s3.Extract(dt); // 0 Extraction.Extract
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				if (_g5)
				{
					long t8 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span8) : 0L;
					_s5.Last(dt); // -500 SceneSystem.Last
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span8, t8);
				}
				if (_g4)
				{
					long t9 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span9) : 0L;
					_s4.Finish(dt); // 0 Late.Finish
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span9, t9);
				}
				if (_g6)
				{
					long t10 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span10) : 0L;
					_s6.Finish(dt); // 0 Late.Finish
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span10, t10);
				}
				{
					long t11 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span11) : 0L;
					_d11(dt); // 1000 EventSystem.StepEvents
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span11, t11);
				}
			}
			else
			{
				if (_g5) _s5.Last(dt); // -500 SceneSystem.Last
				if (_g4) _s4.Finish(dt); // 0 Late.Finish
				if (_g6) _s6.Finish(dt); // 0 Late.Finish
				_d11(dt); // 1000 EventSystem.StepEvents
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				if (_g5)
				{
					long t12 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span12) : 0L;
					_s5.Destroy(dt); // -500 SceneSystem.Destroy
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span12, t12);
				}
			}
			else
			{
				if (_g5) _s5.Destroy(dt); // -500 SceneSystem.Destroy
			}
		}
	}
}
