// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators). Do not edit.
#nullable enable
#pragma warning disable CS0618 // Legacy middleware APIs are intercepted too.

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonInterceptors
	{
		// Program.cs(32,3): UseSystem Menu (TestApp#0)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Trkm8FmgHR37qGfpE+UDv4gDAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Extensions.Scenes.ISceneBuilder UseSystem_0(this global::Ion.Extensions.Scenes.ISceneBuilder scene)
		{
			global::System.ArgumentNullException.ThrowIfNull(scene);
			scene.Schedule.AddSystem(IonSystems.S0, "TestApp#0");
			return scene;
		}

		// Program.cs(33,3): Render function App.lambda(ICurrentScene) (TestApp#1)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Trkm8FmgHR37qGfpE+UDv6MDAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Extensions.Scenes.ISceneBuilder Render_1(this global::Ion.Extensions.Scenes.ISceneBuilder builder, global::System.Action<global::Ion.GameTime, global::Ion.Extensions.Scenes.ICurrentScene> step, int order, string? name)
		{
			builder.Schedule.AddFunction(global::Ion.Stage.Render, step, new global::System.Type[] { typeof(global::Ion.Extensions.Scenes.ICurrentScene) }, services => global::Ion.StepAdapters.FromFunction(step, global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Ion.Extensions.Scenes.ICurrentScene>(services)), order, name ?? "App.lambda(ICurrentScene)", global::System.Type.EmptyTypes, global::System.Type.EmptyTypes, "TestApp#1");
			return builder;
		}

		// Program.cs(30,2): UseScene Scene 1
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Trkm8FmgHR37qGfpE+UDv18DAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseScene_2(this global::Ion.IIonApplication app, global::Scene sceneId, global::System.Action<global::Ion.Extensions.Scenes.ISceneBuilder> configure)
		{
			return global::Ion.Extensions.Scenes.BuilderExtensions.UseScene(app, (int)sceneId, configure, Schedule0Factory.Instance);
		}

		// Program.cs(35,27): Update function App.lambda() (TestApp#3)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Trkm8FmgHR37qGfpE+UDvyoEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Extensions.Scenes.ISceneBuilder Update_3(this global::Ion.Extensions.Scenes.ISceneBuilder builder, global::System.Action<global::Ion.GameTime> step, int order, string? name)
		{
			builder.Schedule.AddFunction(global::Ion.Stage.Update, step, global::System.Type.EmptyTypes, _ => global::Ion.StepAdapters.FromFunction(step), order, name ?? "App.lambda()", global::System.Type.EmptyTypes, global::System.Type.EmptyTypes, "TestApp#3");
			return builder;
		}

		// Program.cs(35,2): UseScene Scene 2
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Trkm8FmgHR37qGfpE+UDvw8EAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseScene_4(this global::Ion.IIonApplication app, int sceneId, global::System.Action<global::Ion.Extensions.Scenes.ISceneBuilder> configure)
		{
			return global::Ion.Extensions.Scenes.BuilderExtensions.UseScene(app, sceneId, configure, Schedule1Factory.Instance);
		}

		// Program.cs(36,2): Update function App.lambda() (TestApp#5)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Trkm8FmgHR37qGfpE+UDv2UEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication Update_5(this global::Ion.IIonApplication builder, global::System.Action<global::Ion.GameTime> step, int order, string? name)
		{
			builder.Schedule.AddFunction(global::Ion.Stage.Update, step, global::System.Type.EmptyTypes, _ => global::Ion.StepAdapters.FromFunction(step), order, name ?? "App.lambda()", global::System.Type.EmptyTypes, global::System.Type.EmptyTypes, "TestApp#5");
			return builder;
		}

		// Program.cs(37,14): Build: installs the generated schedule the application built at Program.cs:37
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "Trkm8FmgHR37qGfpE+UDv6sEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Core.GameLoop Build_6(this global::Ion.IonApplication receiver)
		{
			receiver.Schedule.UseGenerated(Schedule2Factory.Instance);
			return receiver.Build();
		}
	}

	/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonSystems
	{
		public static readonly global::Ion.GeneratedSystem S0 = new global::Ion.GeneratedSystem(
			typeof(global::Menu),
			typeof(global::Menu),
			"Menu",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Init, global::Ion.GeneratedStepKind.Step, 0, "Open", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Menu)instance!).Open),
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, 0, "Tick", 1)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Menu)instance!).Tick),
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Destroy, global::Ion.GeneratedStepKind.Step, 0, "Close", 2)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Menu)instance!).Close),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());
	}

	/// <summary>The schedule of Scene 1 registered at Program.cs:30: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule0Factory Instance = new Schedule0Factory();

		private Schedule0Factory()
			: base("Scene 1 registered at Program.cs:30",
				new string[] { "TestApp#0", "TestApp#1" },
				new bool[] { false, false },
				new string[][]
				{
					new string[] { "0|S|Open|0" }, // Init
					global::System.Array.Empty<string>(), // First
					global::System.Array.Empty<string>(), // FixedUpdate
					new string[] { "0|S|Tick|1" }, // Update
					new string[] { "1|F||0" }, // Render
					global::System.Array.Empty<string>(), // Last
					new string[] { "0|S|Close|2" } // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule0(context);
	}

	/// <summary>The stages of Scene 1 registered at Program.cs:30 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0 : global::Ion.GeneratedSchedule
	{
		private readonly global::Menu _s0;
		private readonly global::System.Action<global::Ion.GameTime, global::Ion.Extensions.Scenes.ICurrentScene> _f2;
		private readonly global::Ion.Extensions.Scenes.ICurrentScene _f2_0;

		public Schedule0(global::Ion.GeneratedScheduleContext context)
		{
			_s0 = context.System<global::Menu>(0);
			_f2 = context.Function<global::System.Action<global::Ion.GameTime, global::Ion.Extensions.Scenes.ICurrentScene>>(1);
			_f2_0 = context.Service<global::Ion.Extensions.Scenes.ICurrentScene>(1);
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
			_s0.Open(dt); // 0 Menu.Open
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			_s0.Tick(dt); // 0 Menu.Tick
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
			_f2(dt, _f2_0); // 0 App.lambda(ICurrentScene) (function)
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
			_s0.Close(dt); // 0 Menu.Close
		}
	}

	/// <summary>The schedule of Scene 2 registered at Program.cs:35: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule1Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule1Factory Instance = new Schedule1Factory();

		private Schedule1Factory()
			: base("Scene 2 registered at Program.cs:35",
				new string[] { "TestApp#3" },
				new bool[] { true },
				new string[][]
				{
					global::System.Array.Empty<string>(), // Init
					global::System.Array.Empty<string>(), // First
					global::System.Array.Empty<string>(), // FixedUpdate
					new string[] { "0|F||0" }, // Update
					global::System.Array.Empty<string>(), // Render
					global::System.Array.Empty<string>(), // Last
					global::System.Array.Empty<string>() // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule1(context);
	}

	/// <summary>The stages of Scene 2 registered at Program.cs:35 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule1 : global::Ion.GeneratedSchedule
	{
		private readonly bool _g0;
		private readonly global::System.Action<global::Ion.GameTime> _f0;

		public Schedule1(global::Ion.GeneratedScheduleContext context)
		{
			_g0 = context.IsActive(0);
			_f0 = context.Function<global::System.Action<global::Ion.GameTime>>(0);
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			if (_g0) _f0(dt); // 0 App.lambda() (function)
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
		}
	}

	/// <summary>The schedule of the application built at Program.cs:37: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule2Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule2Factory Instance = new Schedule2Factory();

		private Schedule2Factory()
			: base("the application built at Program.cs:37",
				new string[] { "Ion.Core#0", "Ion.Extensions.Scenes#0", "Ion.Extensions.Scenes#0", "TestApp#5" },
				new bool[] { false, true, true, false },
				new string[][]
				{
					new string[] { "1|S|Init|0", "2|S|Init|0" }, // Init
					new string[] { "1|S|First|1", "2|S|First|1" }, // First
					new string[] { "1|S|FixedUpdate|2", "2|S|FixedUpdate|2" }, // FixedUpdate
					new string[] { "1|S|Update|3", "2|S|Update|3", "3|F||0" }, // Update
					new string[] { "1|S|Render|4", "2|S|Render|4" }, // Render
					new string[] { "1|S|Last|5", "2|S|Last|5", "0|S|StepEvents|0" }, // Last
					new string[] { "1|S|Destroy|6", "2|S|Destroy|6" } // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule2(context);
	}

	/// <summary>The stages of the application built at Program.cs:37 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule2 : global::Ion.GeneratedSchedule
	{
		private readonly bool _g1;
		private readonly global::Ion.Extensions.Scenes.SceneSystem _s1;
		private readonly bool _g2;
		private readonly global::Ion.Extensions.Scenes.SceneSystem _s2;
		private readonly global::System.Action<global::Ion.GameTime> _f8;
		private readonly global::Ion.GameLoopDelegate _d13;

		public Schedule2(global::Ion.GeneratedScheduleContext context)
		{
			_g1 = context.IsActive(1);
			_s1 = context.System<global::Ion.Extensions.Scenes.SceneSystem>(1);
			_g2 = context.IsActive(2);
			_s2 = context.System<global::Ion.Extensions.Scenes.SceneSystem>(2);
			_f8 = context.Function<global::System.Action<global::Ion.GameTime>>(3);
			_d13 = context.Step(0, global::Ion.Stage.Last, "StepEvents", 0);
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
			if (_g1) _s1.Init(dt); // -500 SceneSystem.Init
			if (_g2) _s2.Init(dt); // -500 SceneSystem.Init
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
			if (_g1) _s1.First(dt); // -500 SceneSystem.First
			if (_g2) _s2.First(dt); // -500 SceneSystem.First
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
			if (_g1) _s1.FixedUpdate(dt); // -500 SceneSystem.FixedUpdate
			if (_g2) _s2.FixedUpdate(dt); // -500 SceneSystem.FixedUpdate
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			if (_g1) _s1.Update(dt); // -500 SceneSystem.Update
			if (_g2) _s2.Update(dt); // -500 SceneSystem.Update
			_f8(dt); // 0 App.lambda() (function)
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
			if (_g1) _s1.Render(dt); // -500 SceneSystem.Render
			if (_g2) _s2.Render(dt); // -500 SceneSystem.Render
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
			if (_g1) _s1.Last(dt); // -500 SceneSystem.Last
			if (_g2) _s2.Last(dt); // -500 SceneSystem.Last
			_d13(dt); // 1000 EventSystem.StepEvents
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
			if (_g1) _s1.Destroy(dt); // -500 SceneSystem.Destroy
			if (_g2) _s2.Destroy(dt); // -500 SceneSystem.Destroy
		}
	}
}
