// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators). Do not edit.
#nullable enable
#pragma warning disable CS0618 // Legacy middleware APIs are intercepted too.

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonInterceptors
	{
		// Program.cs(40,3): UseSystem Sprites (TestApp#0)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "LZ4YOZH4t8B/Byj0yHhn+9AFAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_0(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S0, "TestApp#0");
			return app;
		}

		// Program.cs(40,3): UseSystem Batch (TestApp#1)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "LZ4YOZH4t8B/Byj0yHhn++UFAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_1(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S1, "TestApp#1");
			return app;
		}

		// Program.cs(40,3): UseSystem Frame (TestApp#2)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "LZ4YOZH4t8B/Byj0yHhn+/gFAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_2(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S2, "TestApp#2");
			return app;
		}

		// Program.cs(41,14): Build: installs the generated schedule the application built at Program.cs:41
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "LZ4YOZH4t8B/Byj0yHhn+x0GAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Core.GameLoop Build_3(this global::Ion.IonApplication receiver)
		{
			receiver.Schedule.UseGenerated(Schedule0Factory.Instance);
			return receiver.Build();
		}
	}

	/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonSystems
	{
		public static readonly global::Ion.GeneratedSystem S0 = new global::Ion.GeneratedSystem(
			typeof(global::Sprites),
			typeof(global::Sprites),
			"Sprites",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Step, 0, "Draw", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Sprites)instance!).Draw),
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Step, 0, "Tick", 1)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Sprites)instance!).Tick),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		public static readonly global::Ion.GeneratedSystem S1 = new global::Ion.GeneratedSystem(
			typeof(global::Batch),
			typeof(global::Batch),
			"Batch",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Scope, -850, "Open", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Batch)instance!).Open),
					EndMethod = "Close",
					EndServices = new global::System.Type[] { typeof(global::Ion.ILoopContext) },
					BindEnd = static (instance, services) => new S1_Close_0((global::Batch)instance!, services).Invoke,
					ScopeName = "sprites",
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Update, global::Ion.GeneratedStepKind.Scope, 0, "Start", 2)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Batch)instance!).Start),
					EndMethod = "Stop",
					BindEnd = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Batch)instance!).Stop),
					ScopeName = "profile",
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		public static readonly global::Ion.GeneratedSystem S2 = new global::Ion.GeneratedSystem(
			typeof(global::Frame),
			typeof(global::Frame),
			"Frame",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Scope, -900, "Begin", 0)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Frame)instance!).Begin),
					EndMethod = "End",
					BindEnd = static (instance, services) => global::Ion.StepAdapters.FromAction(((global::Frame)instance!).End),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
		[global::System.Diagnostics.DebuggerNonUserCode]
		[global::System.Diagnostics.StackTraceHidden]
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		private sealed class S1_Close_0
		{
			private readonly global::Batch _system;
			private readonly global::Ion.ILoopContext _p0;

			public S1_Close_0(global::Batch system, global::System.IServiceProvider services)
			{
				_system = system;
				_p0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Ion.ILoopContext>(services);
			}

			[global::System.Diagnostics.StackTraceHidden]
			public void Invoke(global::Ion.GameTime dt) => _system.Close(dt, _p0);
		}
	}

	/// <summary>The schedule of the application built at Program.cs:41: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule0Factory Instance = new Schedule0Factory();

		private Schedule0Factory()
			: base("the application built at Program.cs:41",
				new string[] { "TestApp#0", "TestApp#1", "TestApp#2" },
				new bool[] { false, false, false },
				new string[][]
				{
					global::System.Array.Empty<string>(), // Init
					global::System.Array.Empty<string>(), // First
					global::System.Array.Empty<string>(), // FixedUpdate
					new string[] { "1|B|Start|2", "0|S|Tick|1" }, // Update
					new string[] { "2|B|Begin|0", "1|B|Open|0", "0|S|Draw|0" }, // Render
					global::System.Array.Empty<string>(), // Last
					global::System.Array.Empty<string>() // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule0(context);
	}

	/// <summary>The stages of the application built at Program.cs:41 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0 : global::Ion.GeneratedSchedule
	{
		private readonly global::Ion.FrameProfiler _prof;
		private readonly global::Batch _s1;
		private readonly global::Ion.SpanId _span0;
		private readonly global::Sprites _s0;
		private readonly global::Ion.SpanId _span1;
		private readonly global::Frame _s2;
		private readonly global::Ion.SpanId _span2;
		private readonly global::Ion.ILoopContext _e4_0;
		private readonly global::Ion.SpanId _span3;
		private readonly global::Ion.SpanId _span4;

		public Schedule0(global::Ion.GeneratedScheduleContext context)
		{
			_prof = context.Profiler;
			_s1 = context.System<global::Batch>(1);
			_span0 = global::Ion.MetricsIds.Register("Batch.Start");
			_s0 = context.System<global::Sprites>(0);
			_span1 = global::Ion.MetricsIds.Register("Sprites.Tick");
			_s2 = context.System<global::Frame>(2);
			_span2 = global::Ion.MetricsIds.Register("Frame.Begin");
			_e4_0 = context.Service<global::Ion.ILoopContext>(1);
			_span3 = global::Ion.MetricsIds.Register("Batch.Open");
			_span4 = global::Ion.MetricsIds.Register("Sprites.Draw");
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				// 0 Batch.Start ... Batch.Stop
				long t0 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span0) : 0L;
				_s1.Start(dt);
				try
				{
					{
						long t1 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span1) : 0L;
						_s0.Tick(dt); // 0 Sprites.Tick
						if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span1, t1);
					}
				}
				finally
				{
					_s1.Stop(dt);
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span0, t0);
				}
			}
			else
			{
				// 0 Batch.Start ... Batch.Stop
				_s1.Start(dt);
				try
				{
					_s0.Tick(dt); // 0 Sprites.Tick
				}
				finally
				{
					_s1.Stop(dt);
				}
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				// -900 Frame.Begin ... Frame.End
				long t2 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span2) : 0L;
				_s2.Begin(dt);
				try
				{
					// -850 Batch.Open ... Batch.Close
					long t3 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span3) : 0L;
					_s1.Open(dt);
					try
					{
						{
							long t4 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span4) : 0L;
							_s0.Draw(dt); // 0 Sprites.Draw
							if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span4, t4);
						}
					}
					finally
					{
						_s1.Close(dt, _e4_0);
						if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span3, t3);
					}
				}
				finally
				{
					_s2.End();
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span2, t2);
				}
			}
			else
			{
				// -900 Frame.Begin ... Frame.End
				_s2.Begin(dt);
				try
				{
					// -850 Batch.Open ... Batch.Close
					_s1.Open(dt);
					try
					{
						_s0.Draw(dt); // 0 Sprites.Draw
					}
					finally
					{
						_s1.Close(dt, _e4_0);
					}
				}
				finally
				{
					_s2.End();
				}
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
		}
	}
}
