// <auto-generated/>
// Generated by the Ion schedule generator (Ion.Generators). Do not edit.
#nullable enable
#pragma warning disable CS0618 // Legacy middleware APIs are intercepted too.

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
	file sealed class InterceptsLocationAttribute : global::System.Attribute
	{
		public InterceptsLocationAttribute(int version, string data)
		{
			_ = version;
			_ = data;
		}
	}
}

namespace Ion.Generated
{
	/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonInterceptors
	{
		// Program.cs(35,3): UseSystem Paddle (TestApp#0)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "K5dlHXSz91W24wPMVgA32E0EAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_0(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S0, "TestApp#0");
			return app;
		}

		// Program.cs(35,3): UseSystem Physics (TestApp#1)
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "K5dlHXSz91W24wPMVgA32GEEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.IIonApplication UseSystem_1(this global::Ion.IIonApplication app)
		{
			global::System.ArgumentNullException.ThrowIfNull(app);
			app.Schedule.AddSystem(IonSystems.S1, "TestApp#1");
			return app;
		}

		// Program.cs(36,14): Build: installs the generated schedule the application built at Program.cs:36
		[global::System.Runtime.CompilerServices.InterceptsLocation(1, "K5dlHXSz91W24wPMVgA32IgEAABQcm9ncmFtLmNz")]
		[global::System.Diagnostics.StackTraceHidden]
		public static global::Ion.Core.GameLoop Build_2(this global::Ion.IonApplication receiver)
		{
			receiver.Schedule.UseGenerated(Schedule0Factory.Instance);
			return receiver.Build();
		}
	}

	/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file static class IonSystems
	{
		public static readonly global::Ion.GeneratedSystem S0 = new global::Ion.GeneratedSystem(
			typeof(global::Paddle),
			typeof(global::Paddle),
			"Paddle",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.FixedUpdate, global::Ion.GeneratedStepKind.Step, -10, "Move", 0)
				{
					After = new global::System.Type[] { typeof(global::Physics) },
					Services = new global::System.Type[] { typeof(global::Clock) },
					Bind = static (instance, services) => new S0_Move_0((global::Paddle)instance!, services).Invoke,
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.Render, global::Ion.GeneratedStepKind.Step, 0, "Draw", 1)
				{
					IsStatic = true,
					After = new global::System.Type[] { typeof(global::Physics) },
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(global::Paddle.Draw),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		public static readonly global::Ion.GeneratedSystem S1 = new global::Ion.GeneratedSystem(
			typeof(global::Physics),
			typeof(global::Physics),
			"Physics",
			new global::Ion.GeneratedStep[]
			{
				new global::Ion.GeneratedStep(global::Ion.Stage.Init, global::Ion.GeneratedStepKind.Step, 0, "Load", 0)
				{
					Bind = static (instance, services) => global::Ion.StepAdapters.FromAction(((global::Physics)instance!).Load),
				},
				new global::Ion.GeneratedStep(global::Ion.Stage.FixedUpdate, global::Ion.GeneratedStepKind.Step, 0, "Step", 1)
				{
					Bind = static (instance, services) => new global::Ion.GameLoopDelegate(((global::Physics)instance!).Step),
				}
			},
			global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());

		[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
		[global::System.Diagnostics.DebuggerNonUserCode]
		[global::System.Diagnostics.StackTraceHidden]
		[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		private sealed class S0_Move_0
		{
			private readonly global::Paddle _system;
			private readonly global::Clock _p0;

			public S0_Move_0(global::Paddle system, global::System.IServiceProvider services)
			{
				_system = system;
				_p0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Clock>(services);
			}

			[global::System.Diagnostics.StackTraceHidden]
			public void Invoke(global::Ion.GameTime dt) => _system.Move(dt, _p0);
		}
	}

	/// <summary>The schedule of the application built at Program.cs:36: the registrations the generator saw and their plan.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0Factory : global::Ion.GeneratedScheduleFactory
	{
		public static readonly Schedule0Factory Instance = new Schedule0Factory();

		private Schedule0Factory()
			: base("the application built at Program.cs:36",
				new string[] { "TestApp#0", "TestApp#1" },
				new bool[] { false, false },
				new string[][]
				{
					new string[] { "1|S|Load|0" }, // Init
					global::System.Array.Empty<string>(), // First
					new string[] { "1|S|Step|1", "0|S|Move|0" }, // FixedUpdate
					global::System.Array.Empty<string>(), // Update
					new string[] { "0|S|Draw|1" }, // Render
					global::System.Array.Empty<string>(), // Last
					global::System.Array.Empty<string>() // Destroy
				})
		{
		}

		protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new Schedule0(context);
	}

	/// <summary>The stages of the application built at Program.cs:36 as direct calls, in plan order.</summary>
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Generators", "0.3.0")]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.StackTraceHidden]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	file sealed class Schedule0 : global::Ion.GeneratedSchedule
	{
		private readonly global::Ion.FrameProfiler _prof;
		private readonly global::Physics _s1;
		private readonly global::Ion.SpanId _span0;
		private readonly global::Ion.SpanId _span1;
		private readonly global::Clock _p3_0;
		private readonly global::Paddle _s0;
		private readonly global::Ion.SpanId _span2;
		private readonly global::Ion.SpanId _span3;

		public Schedule0(global::Ion.GeneratedScheduleContext context)
		{
			_prof = context.Profiler;
			_s1 = context.System<global::Physics>(1);
			_span0 = global::Ion.MetricsIds.Register("Physics.Load");
			_span1 = global::Ion.MetricsIds.Register("Physics.Step");
			_p3_0 = context.Service<global::Clock>(0);
			_s0 = context.System<global::Paddle>(0);
			_span2 = global::Ion.MetricsIds.Register("Paddle.Move");
			_span3 = global::Ion.MetricsIds.Register("Paddle.Draw");
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Init(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t0 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span0) : 0L;
					_s1.Load(); // 0 Physics.Load
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span0, t0);
				}
			}
			else
			{
				_s1.Load(); // 0 Physics.Load
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void First(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void FixedUpdate(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t1 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span1) : 0L;
					_s1.Step(dt); // 0 Physics.Step
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span1, t1);
				}
				{
					long t2 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span2) : 0L;
					_s0.Move(dt, _p3_0); // -10 Paddle.Move
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span2, t2);
				}
			}
			else
			{
				_s1.Step(dt); // 0 Physics.Step
				_s0.Move(dt, _p3_0); // -10 Paddle.Move
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Update(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Render(global::Ion.GameTime dt)
		{
			if (global::Ion.FrameProfiler.IsProfilingEnabled && _prof.IsActive)
			{
				{
					long t3 = global::Ion.FrameProfiler.IsProfilingEnabled ? _prof.Begin(_span3) : 0L;
					global::Paddle.Draw(dt); // 0 Paddle.Draw
					if (global::Ion.FrameProfiler.IsProfilingEnabled) _prof.End(_span3, t3);
				}
			}
			else
			{
				global::Paddle.Draw(dt); // 0 Paddle.Draw
			}
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Last(global::Ion.GameTime dt)
		{
		}

		[global::System.Diagnostics.StackTraceHidden]
		public override void Destroy(global::Ion.GameTime dt)
		{
		}
	}
}
