# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
        - break
    - title: ✨ Features
      labels:
        - feature
        - new
        - update
    - title: 🐛 Fixes
      labels: 
        - fix
    - title: Other Changes
      labels:
        - "*"