using System.Globalization;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Ion.Generators;

/// <summary>
/// Writes the generated file: the <c>ScheduleRegistrations</c> summaries, the interceptors, the system descriptions
/// (with their hidden step adapters) and one <c>GeneratedSchedule</c> per application and scene. Every generated type is
/// file-local, so assemblies that see each other's internals never clash.
/// </summary>
internal sealed class Emitter(KnownSymbols known, RegistrationAnalyzer registrations, bool profiling = true)
{
	private const string ProfilingEnabled = "global::Ion.FrameProfiler.IsProfilingEnabled";

	// Brackets every step and scope of the generated stage methods with profiler timestamps (see WriteItems), unless the
	// project set <IonMetricsProfiling>false</IonMetricsProfiling> or the engine predates the frame profiler.
	private readonly bool _profiling = profiling && known.FrameProfiler is not null;

	private const string GeneratorName = "Ion.Generators";
	private const string GeneratorVersion = "0.3.0";

	private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat;
	private static readonly SymbolDisplayFormat SignatureFormat = SymbolDisplayFormat.FullyQualifiedFormat
		.AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

	private readonly Dictionary<SystemInfo, int> _systemIndexes = [];
	private readonly List<SystemInfo> _systems = [];

	public string Emit(
		IReadOnlyList<InterceptedCall> calls,
		IReadOnlyList<ScheduleCandidate> candidates,
		IReadOnlyList<(string Key, string Ops, List<ITypeSymbol> Types)> summaries)
	{
		var w = new SourceWriter();
		w.WriteLine("// <auto-generated/>");
		w.WriteLine("// Generated by the Ion schedule generator (Ion.Generators). Do not edit.");
		w.WriteLine("#nullable enable");
		w.WriteLine("#pragma warning disable CS0618 // Legacy middleware APIs are intercepted too.");
		w.WriteEmptyLines(1);

		foreach (var (key, ops, types) in summaries)
		{
			var typeList = types.Count == 0 ? "" : ", " + string.Join(", ", types.Select(t => $"typeof({Type(t)})"));
			w.WriteLine($"[assembly: global::Ion.ScheduleRegistrationsAttribute({Literal(key)}, {Literal(ops)}{typeList})]");
		}

		if (summaries.Count > 0) w.WriteEmptyLines(1);

		foreach (var call in calls.Where(c => c.Kind == CallKind.UseSystem)) SystemIndex(call.System!);

		var interceptorCalls = calls.Where(c => c.Kind is not (CallKind.UseScene or CallKind.Root) || c.Candidate is { Invalid: null }).ToList();
		if (interceptorCalls.Count > 0)
		{
			w.WriteLine("namespace System.Runtime.CompilerServices");
			w.OpenBlock();
			w.WriteLine("[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
			w.WriteLine("file sealed class InterceptsLocationAttribute : global::System.Attribute");
			w.OpenBlock();
			w.WriteLine("public InterceptsLocationAttribute(int version, string data)");
			w.OpenBlock();
			w.WriteLine("_ = version;");
			w.WriteLine("_ = data;");
			w.CloseBlock();
			w.CloseBlock();
			w.CloseBlock();
			w.WriteEmptyLines(1);
		}

		w.WriteLine("namespace Ion.Generated");
		w.OpenBlock();

		if (interceptorCalls.Count > 0)
		{
			WriteInterceptors(w, interceptorCalls);
			w.WriteEmptyLines(1);
		}

		if (_systems.Count > 0)
		{
			WriteSystems(w);
			w.WriteEmptyLines(1);
		}

		foreach (var candidate in candidates.Where(c => c.Invalid is null))
		{
			WriteSchedule(w, candidate);
			w.WriteEmptyLines(1);
		}

		w.CloseBlock();
		return w.ToString().Replace("\n\n}", "\n}").TrimEnd('\n') + "\n";
	}

	private int SystemIndex(SystemInfo system)
	{
		if (!_systemIndexes.TryGetValue(system, out var index))
		{
			index = _systems.Count;
			_systems.Add(system);
			_systemIndexes[system] = index;
		}

		return index;
	}

	private static void WriteTypeAttributes(SourceWriter w)
	{
		w.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{GeneratorName}\", \"{GeneratorVersion}\")]");
		w.WriteLine("[global::System.Diagnostics.DebuggerNonUserCode]");
		w.WriteLine("[global::System.Diagnostics.StackTraceHidden]");
		w.WriteLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
	}

	#region Interceptors

	private void WriteInterceptors(SourceWriter w, List<InterceptedCall> calls)
	{
		w.WriteLine("/// <summary>Replaces the registration calls of this assembly with pre-bound, reflection-free registrations.</summary>");
		WriteTypeAttributes(w);
		w.WriteLine("file static class IonInterceptors");
		w.OpenBlock();

		var first = true;
		foreach (var call in calls.OrderBy(c => c.Index))
		{
			if (!first) w.WriteEmptyLines(1);
			first = false;

			var method = call.Method;
			var location = call.Invocation.GetLocation().GetLineSpan();
			w.WriteLine($"// {System.IO.Path.GetFileName(location.Path)}({(location.StartLinePosition.Line + 1).ToString(CultureInfo.InvariantCulture)},{(location.StartLinePosition.Character + 1).ToString(CultureInfo.InvariantCulture)}): {Describe(call)}");
			w.WriteLine($"[{call.Attribute}]");
			w.WriteLine("[global::System.Diagnostics.StackTraceHidden]");

			var parameters = new List<(string Type, string Name)>();
			var isInstance = !method.IsStatic;
			if (isInstance) parameters.Add((method.ContainingType.ToDisplayString(SignatureFormat), "receiver"));
			foreach (var parameter in method.Parameters) parameters.Add((parameter.Type.ToDisplayString(SignatureFormat), Identifier(parameter.Name)));

			var signature = string.Join(", ", parameters.Select((p, i) => (i == 0 ? "this " : "") + p.Type + " " + p.Name));
			var returnType = method.ReturnsVoid ? "void" : method.ReturnType.ToDisplayString(SignatureFormat);
			var receiver = parameters[0].Name;

			w.WriteLine($"public static {returnType} {MethodName(call)}({signature})");
			w.OpenBlock();

			switch (call.Kind)
			{
				case CallKind.UseSystem:
					w.WriteLine($"global::System.ArgumentNullException.ThrowIfNull({receiver});");
					w.WriteLine($"{receiver}.Schedule.AddSystem(IonSystems.S{SystemIndex(call.System!).ToString(CultureInfo.InvariantCulture)}, {Literal(call.Site)});");
					w.WriteLine($"return {receiver};");
					break;

				case CallKind.Function:
				{
					var step = parameters[1].Name;
					var services = call.Services;
					var bind = services.Count == 0
						? $"_ => global::Ion.StepAdapters.FromFunction({step})"
						: $"services => global::Ion.StepAdapters.FromFunction({step}, {string.Join(", ", services.Select(s => Resolve(s, "services")))})";
					w.WriteLine($"{receiver}.Schedule.AddFunction(global::Ion.Stage.{KnownSymbols.StageName(call.Stage)}, {step}, {TypeArray(services)}, {bind}, {parameters[2].Name}, {parameters[3].Name}{(call.Name is null ? "" : " ?? " + Literal(call.Name))}, {NullableTypeArray(call.After)}, {NullableTypeArray(call.Before)}, {Literal(call.Site)});");
					w.WriteLine($"return {receiver};");
					break;
				}

				case CallKind.Middleware:
					w.WriteLine($"{receiver}.Schedule.AddMiddleware(global::Ion.Stage.{KnownSymbols.StageName(call.Stage)}, {parameters[1].Name}, 0, {(call.Name is null ? "null" : Literal(call.Name))}, {Literal(call.Site)});");
					w.WriteLine($"return {receiver};");
					break;

				case CallKind.DelegateServicesMiddleware:
				{
					var services = string.Join(", ", call.Services.Select(s => Resolve(s, receiver + ".Services")));
					w.WriteLine($"{receiver}.Schedule.AddMiddleware(global::Ion.Stage.{KnownSymbols.StageName(call.Stage)}, next => {parameters[1].Name}(next, {services}), 0, {Literal(call.Name!)}, {Literal(call.Site)});");
					w.WriteLine($"return {receiver};");
					break;
				}

				case CallKind.UseScene:
				{
					var id = KnownSymbols.Is(method.Parameters[1].Type, known.Compilation.GetSpecialType(SpecialType.System_Int32)) ? parameters[1].Name : $"(int){parameters[1].Name}";
					w.WriteLine($"return global::Ion.Extensions.Scenes.BuilderExtensions.UseScene({receiver}, {id}, {parameters[2].Name}, Schedule{call.Candidate!.ClassIndex.ToString(CultureInfo.InvariantCulture)}Factory.Instance);");
					break;
				}

				case CallKind.Root:
				{
					w.WriteLine($"{receiver}.Schedule.UseGenerated(Schedule{call.Candidate!.ClassIndex.ToString(CultureInfo.InvariantCulture)}Factory.Instance);");
					var arguments = string.Join(", ", parameters.Skip(1).Select(p => p.Name));
					w.WriteLine($"{(method.ReturnsVoid ? "" : "return ")}{receiver}.{method.Name}({arguments});");
					break;
				}
			}

			w.CloseBlock();
		}

		w.CloseBlock();
	}

	private static string MethodName(InterceptedCall call) => call.Kind switch
	{
		CallKind.Root or CallKind.Middleware or CallKind.DelegateServicesMiddleware or CallKind.Function or CallKind.UseScene or CallKind.UseSystem => call.Method.Name + "_" + call.Index.ToString(CultureInfo.InvariantCulture),
		_ => "Intercept_" + call.Index.ToString(CultureInfo.InvariantCulture),
	};

	private static string Describe(InterceptedCall call) => call.Kind switch
	{
		CallKind.UseSystem => $"UseSystem {call.System!.Name} ({call.Site})",
		CallKind.Function => $"{KnownSymbols.StageName(call.Stage)} function {call.Name ?? "(named at run time)"} ({call.Site})",
		CallKind.Middleware or CallKind.DelegateServicesMiddleware => $"{KnownSymbols.StageName(call.Stage)} legacy middleware {call.Name ?? "(named at run time)"} ({call.Site})",
		CallKind.UseScene => $"UseScene {call.Candidate!.ScheduleName}",
		_ => $"{call.Method.Name}: installs the generated schedule {call.Candidate!.Name}",
	};

	#endregion

	#region Systems

	private void WriteSystems(SourceWriter w)
	{
		w.WriteLine("/// <summary>The systems registered by this assembly, described at compile time (no reflection).</summary>");
		WriteTypeAttributes(w);
		w.WriteLine("file static class IonSystems");
		w.OpenBlock();

		var adapters = new List<(string Name, SystemInfo System, IMethodSymbol Method)>();
		var queryAdapters = new List<(string Name, SystemInfo System, QueryInfo Query)>();

		for (var s = 0; s < _systems.Count; s++)
		{
			var system = _systems[s];
			var impl = Type(system.Implementation);
			if (s > 0) w.WriteEmptyLines(1);
			w.WriteLine($"public static readonly global::Ion.GeneratedSystem S{s.ToString(CultureInfo.InvariantCulture)} = new global::Ion.GeneratedSystem(");
			w.OpenIndent();
			w.WriteLine($"typeof({Type(system.Service)}),");
			w.WriteLine($"typeof({impl}),");
			w.WriteLine($"{Literal(system.Name)},");

			if (system.Steps.Count == 0)
			{
				w.WriteLine("global::System.Array.Empty<global::Ion.GeneratedStep>(),");
			}
			else
			{
				w.WriteLine("new global::Ion.GeneratedStep[]");
				w.OpenBlock();
				for (var i = 0; i < system.Steps.Count; i++)
				{
					var step = system.Steps[i];
					var kind = step.Kind switch { ItemKind.Scope => "Scope", ItemKind.Middleware => "Middleware", _ => "Step" };
					w.WriteLine($"new global::Ion.GeneratedStep(global::Ion.Stage.{KnownSymbols.StageName(step.Stage)}, global::Ion.GeneratedStepKind.{kind}, {step.Order.ToString(CultureInfo.InvariantCulture)}, {Literal(step.Name)}, {step.DeclarationIndex.ToString(CultureInfo.InvariantCulture)})");
					w.OpenBlock();
					if (step.Method.IsStatic) w.WriteLine("IsStatic = true,");
					if (step.After.Count > 0) w.WriteLine($"After = {TypeArray(step.After)},");
					if (step.Before.Count > 0) w.WriteLine($"Before = {TypeArray(step.Before)},");

					if (step.Kind == ItemKind.Middleware)
					{
						w.WriteLine($"BindMiddleware = {BindMiddleware(system, step.Method, step.Signature)},");
					}
					else if (step.Query is { } query)
					{
						w.WriteLine($"Services = {TypeArray(QueryServices(query))},");
						w.WriteLine($"Bind = {BindQuery(system, s, query, queryAdapters)},");
					}
					else
					{
						var services = ServicesOf(step.Method, step.Signature);
						if (services.Count > 0) w.WriteLine($"Services = {TypeArray(services)},");
						w.WriteLine($"Bind = {Bind(system, s, step.Method, step.Signature, adapters)},");
					}

					if (step.EndMethod is { } end)
					{
						w.WriteLine($"EndMethod = {Literal(end.Name)},");
						if (end.IsStatic) w.WriteLine("EndIsStatic = true,");
						var endServices = ServicesOf(end, step.EndSignature);
						if (endServices.Count > 0) w.WriteLine($"EndServices = {TypeArray(endServices)},");
						w.WriteLine($"BindEnd = {Bind(system, s, end, step.EndSignature, adapters)},");
						if (step.ScopeName is not null) w.WriteLine($"ScopeName = {Literal(step.ScopeName)},");
					}

					w.CloseBlock(i == system.Steps.Count - 1 ? "" : ",");
				}

				w.CloseBlock(",");
			}

			if (system.Diagnostics.Count == 0)
			{
				w.WriteLine("global::System.Array.Empty<global::Ion.ScheduleDiagnostic>());");
			}
			else
			{
				w.WriteLine("new global::Ion.ScheduleDiagnostic[]");
				w.OpenBlock();
				foreach (var diagnostic in system.Diagnostics)
				{
					w.WriteLine($"new global::Ion.ScheduleDiagnostic({Literal(diagnostic.Code)}, global::Ion.ScheduleDiagnosticSeverity.{(diagnostic.IsError ? "Error" : "Warning")}, {Literal(diagnostic.Message)}),");
				}

				w.CloseBlock(");");
			}

			w.CloseIndent();
		}

		foreach (var (name, system, method) in adapters)
		{
			w.WriteEmptyLines(1);
			WriteAdapter(w, name, system, method);
		}

		foreach (var (name, system, query) in queryAdapters)
		{
			w.WriteEmptyLines(1);
			WriteQueryAdapter(w, name, system, query);
		}

		w.CloseBlock();
	}

	private List<ITypeSymbol> ServicesOf(IMethodSymbol method, SignatureKind signature) =>
		signature == SignatureKind.Injected ? method.Parameters.Select(p => p.Type).Where(t => !KnownSymbols.Is(t, known.GameTime)).ToList() : [];

	private string Bind(SystemInfo system, int index, IMethodSymbol method, SignatureKind signature, List<(string, SystemInfo, IMethodSymbol)> adapters)
	{
		var target = Target(system, method);
		switch (signature)
		{
			case SignatureKind.GameTime:
				return $"static (instance, services) => new global::Ion.GameLoopDelegate({target}.{method.Name})";
			case SignatureKind.NoArguments:
				return $"static (instance, services) => global::Ion.StepAdapters.FromAction({target}.{method.Name})";
			default:
				var name = $"S{index.ToString(CultureInfo.InvariantCulture)}_{method.Name}_{adapters.Count.ToString(CultureInfo.InvariantCulture)}";
				adapters.Add((name, system, method));
				return method.IsStatic
					? $"static (instance, services) => new {name}(services).Invoke"
					: $"static (instance, services) => new {name}(({Type(system.Implementation)})instance!, services).Invoke";
		}
	}

	private List<ITypeSymbol> QueryServices(QueryInfo query) => query.UsesCommands ? [known.ArchWorld!, known.Commands!] : [known.ArchWorld!];

	private string BindQuery(SystemInfo system, int index, QueryInfo query, List<(string, SystemInfo, QueryInfo)> adapters)
	{
		var name = $"S{index.ToString(CultureInfo.InvariantCulture)}_{query.Method.Name}_Query{adapters.Count.ToString(CultureInfo.InvariantCulture)}";
		adapters.Add((name, system, query));
		return query.Method.IsStatic
			? $"static (instance, services) => new {name}(services).Invoke"
			: $"static (instance, services) => new {name}(({Type(system.Implementation)})instance!, services).Invoke";
	}

	/// <summary>Binds a [Query] step: its expansion with the scope's world (and commands) resolved once.</summary>
	private void WriteQueryAdapter(SourceWriter w, string name, SystemInfo system, QueryInfo query)
	{
		var isStatic = query.Method.IsStatic;
		WriteTypeAttributes(w);
		w.WriteLine($"private sealed class {name}");
		w.OpenBlock();
		if (!isStatic) w.WriteLine($"private readonly {Type(system.Implementation)} _system;");
		w.WriteLine($"private readonly {Type(known.ArchWorld!)} _world;");
		if (query.UsesCommands) w.WriteLine($"private readonly {Type(known.Commands!)} _commands;");
		w.WriteEmptyLines(1);
		w.WriteLine(isStatic
			? $"public {name}(global::System.IServiceProvider services)"
			: $"public {name}({Type(system.Implementation)} system, global::System.IServiceProvider services)");
		w.OpenBlock();
		if (!isStatic) w.WriteLine("_system = system;");
		w.WriteLine($"_world = {Resolve(known.ArchWorld!, "services")};");
		if (query.UsesCommands) w.WriteLine($"_commands = {Resolve(known.Commands!, "services")};");
		w.CloseBlock();
		w.WriteEmptyLines(1);
		w.WriteLine("[global::System.Diagnostics.StackTraceHidden]");
		w.WriteLine($"public void Invoke(global::Ion.GameTime dt) => {(isStatic ? Type(query.Method.ContainingType) : "_system")}.{query.CompanionName}(dt, _world{(query.UsesCommands ? ", _commands" : "")});");
		w.CloseBlock();
	}

	private string BindMiddleware(SystemInfo system, IMethodSymbol method, SignatureKind signature)
	{
		var target = Target(system, method);
		return signature == SignatureKind.LegacyFactory
			? $"static (instance, services) => new global::System.Func<global::Ion.GameLoopDelegate, global::Ion.GameLoopDelegate>({target}.{method.Name})"
			: $"static (instance, services) => global::Ion.StepAdapters.FromMiddleware({target}.{method.Name})";
	}

	private string Target(SystemInfo system, IMethodSymbol method) =>
		method.IsStatic ? Type(method.ContainingType) : $"(({Type(system.Implementation)})instance!)";

	private void WriteAdapter(SourceWriter w, string name, SystemInfo system, IMethodSymbol method)
	{
		WriteTypeAttributes(w);
		w.WriteLine($"private sealed class {name}");
		w.OpenBlock();

		if (!method.IsStatic) w.WriteLine($"private readonly {Type(system.Implementation)} _system;");
		var arguments = new List<string>();
		var fields = new List<(string Name, ITypeSymbol Type)>();
		foreach (var parameter in method.Parameters)
		{
			if (KnownSymbols.Is(parameter.Type, known.GameTime))
			{
				arguments.Add("dt");
				continue;
			}

			var field = "_p" + fields.Count.ToString(CultureInfo.InvariantCulture);
			fields.Add((field, parameter.Type));
			arguments.Add(field);
			w.WriteLine($"private readonly {Type(parameter.Type)} {field};");
		}

		w.WriteEmptyLines(1);
		w.WriteLine(method.IsStatic
			? $"public {name}(global::System.IServiceProvider services)"
			: $"public {name}({Type(system.Implementation)} system, global::System.IServiceProvider services)");
		w.OpenBlock();
		if (!method.IsStatic) w.WriteLine("_system = system;");
		foreach (var (field, type) in fields) w.WriteLine($"{field} = {Resolve(type, "services")};");
		w.CloseBlock();
		w.WriteEmptyLines(1);
		w.WriteLine("[global::System.Diagnostics.StackTraceHidden]");
		w.WriteLine($"public void Invoke(global::Ion.GameTime dt) => {(method.IsStatic ? Type(method.ContainingType) : "_system")}.{method.Name}({string.Join(", ", arguments)});");
		w.CloseBlock();
	}

	#endregion

	#region Schedules

	private sealed class ScheduleWriter
	{
		public List<string> Fields { get; } = [];
		public List<string> Init { get; } = [];
		public List<string> Continuations { get; } = [];
		public List<string> MiddlewareInit { get; } = [];
		public List<(string Name, List<CandidateItem> Items, int Start, int Stage)> ContinuationMethods { get; } = [];
		public HashSet<int> Guards { get; } = [];
		public HashSet<int> Instances { get; } = [];
		public int Items;
		public int Spans;
		public Dictionary<CandidateItem, string> LeafCalls { get; } = [];
		public Dictionary<CandidateItem, (string Begin, string End)> ScopeCalls { get; } = [];
		public Dictionary<CandidateItem, (string Field, string Local)> SpanFields { get; } = [];
		public int Stage;
		public Dictionary<int, List<string>> StageMiddlewareInit { get; } = [];

		// Inserted first: the middleware met later in a stage is nested deeper, and is bound first.
		public void AddMiddleware(string line)
		{
			if (!StageMiddlewareInit.TryGetValue(Stage, out var lines)) StageMiddlewareInit[Stage] = lines = [];
			lines.Insert(0, line);
		}
	}

	private void WriteSchedule(SourceWriter w, ScheduleCandidate candidate)
	{
		var index = candidate.ClassIndex.ToString(CultureInfo.InvariantCulture);
		var className = "Schedule" + index;
		var state = new ScheduleWriter();

		// Stage bodies first: they decide which fields the constructor initializes.
		var bodies = new List<(string Stage, SourceWriter Body)>();
		for (var stage = 1; stage <= 7; stage++)
		{
			var body = new SourceWriter();
			state.Stage = stage;
			WriteStage(body, candidate, state, candidate.Stages[stage - 1], 0, stage);
			bodies.Add((KnownSymbols.StageName(stage), body));
		}

		// Continuations (the rest of a stage after a legacy middleware) are appended while they are written.
		var continuationBodies = new List<(string Name, SourceWriter Body)>();
		for (var c = 0; c < state.ContinuationMethods.Count; c++)
		{
			var (name, items, start, stage) = state.ContinuationMethods[c];
			var body = new SourceWriter();
			state.Stage = stage;
			WriteItems(body, candidate, state, items, start, stage, _profiling);
			continuationBodies.Add((name, body));
		}

		// The runtime binds stages in order and, within a stage, the innermost middleware first.
		for (var stage = 1; stage <= 7; stage++)
		{
			if (state.StageMiddlewareInit.TryGetValue(stage, out var lines)) state.MiddlewareInit.AddRange(lines);
		}

		// Factory: the data the runtime checks before using the schedule.
		w.WriteLine($"/// <summary>The schedule of {Escape(candidate.Name)}: the registrations the generator saw and their plan.</summary>");
		WriteTypeAttributes(w);
		w.WriteLine($"file sealed class {className}Factory : global::Ion.GeneratedScheduleFactory");
		w.OpenBlock();
		w.WriteLine($"public static readonly {className}Factory Instance = new {className}Factory();");
		w.WriteEmptyLines(1);
		w.WriteLine($"private {className}Factory()");
		w.OpenIndent();
		w.WriteLine($": base({Literal(candidate.Name)},");
		w.OpenIndent();
		w.WriteLine(candidate.Entries.Count == 0 ? "global::System.Array.Empty<string>()," : $"new string[] {{ {string.Join(", ", candidate.Entries.Select(e => Literal(e.Site!)))} }},");
		w.WriteLine(candidate.Entries.Count == 0 ? "global::System.Array.Empty<bool>()," : $"new bool[] {{ {string.Join(", ", candidate.Entries.Select(e => e.Conditional ? "true" : "false"))} }},");
		w.WriteLine("new string[][]");
		w.OpenBlock();
		for (var stage = 0; stage < 7; stage++)
		{
			var keys = candidate.Stages[stage].Select(i => Literal(i.Key)).ToList();
			var comment = $" // {KnownSymbols.StageNames[stage]}";
			w.WriteLine((keys.Count == 0 ? "global::System.Array.Empty<string>()" : $"new string[] {{ {string.Join(", ", keys)} }}") + (stage < 6 ? "," : "") + comment);
		}

		w.CloseBlock(")");
		w.CloseIndent();
		w.CloseIndent();
		w.OpenBlock();
		w.CloseBlock();
		w.WriteEmptyLines(1);
		w.WriteLine("protected override global::Ion.GeneratedSchedule Create(global::Ion.GeneratedScheduleContext context) => new " + className + "(context);");
		w.CloseBlock();
		w.WriteEmptyLines(1);

		// The schedule: the composition root in the constructor, one method per stage.
		w.WriteLine($"/// <summary>The stages of {Escape(candidate.Name)} as direct calls, in plan order.</summary>");
		WriteTypeAttributes(w);
		w.WriteLine($"file sealed class {className} : global::Ion.GeneratedSchedule");
		w.OpenBlock();

		foreach (var field in state.Fields) w.WriteLine(field);
		if (state.Fields.Count > 0) w.WriteEmptyLines(1);

		w.WriteLine($"public {className}(global::Ion.GeneratedScheduleContext context)");
		w.OpenBlock();
		foreach (var line in state.Init.Concat(state.Continuations).Concat(state.MiddlewareInit)) w.WriteLine(line);
		w.CloseBlock();

		foreach (var (stage, body) in bodies)
		{
			w.WriteEmptyLines(1);
			w.WriteLine("[global::System.Diagnostics.StackTraceHidden]");
			w.WriteLine($"public override void {stage}(global::Ion.GameTime dt)");
			WriteBody(w, body);
		}

		foreach (var (name, body) in continuationBodies)
		{
			w.WriteEmptyLines(1);
			w.WriteLine("[global::System.Diagnostics.StackTraceHidden]");
			w.WriteLine($"private void {name}(global::Ion.GameTime dt)");
			WriteBody(w, body);
		}

		w.CloseBlock();
	}

	private static void WriteBody(SourceWriter w, SourceWriter body)
	{
		w.OpenBlock();
		foreach (var line in body.ToString().Split('\n'))
		{
			if (line.Length > 0) w.WriteLine(line);
		}

		w.CloseBlock();
	}

	/// <summary>
	/// Writes a stage. With profiling, a stage without legacy middleware is written twice: a copy that brackets every step
	/// and scope, run while the profiler is active, and the plain copy, so a stage costs one check when it is not. (A legacy
	/// middleware splits the stage into continuation methods, which are written once, with the per-step checks.)
	/// </summary>
	private void WriteStage(SourceWriter w, ScheduleCandidate candidate, ScheduleWriter state, List<CandidateItem> items, int start, int stage)
	{
		var split = _profiling && items.Count > start && !items.Any(i => i.Wraps && !i.IsScope);
		if (!split)
		{
			WriteItems(w, candidate, state, items, start, stage, _profiling);
			return;
		}

		EnsureProfilerField(state);
		w.WriteLine($"if ({ProfilingEnabled} && _prof.IsActive)");
		w.OpenBlock();
		WriteItems(w, candidate, state, items, start, stage, profiled: true);
		w.CloseBlock();
		w.WriteLine("else");
		w.OpenBlock();
		WriteItems(w, candidate, state, items, start, stage, profiled: false);
		w.CloseBlock();
	}

	private void WriteItems(SourceWriter w, ScheduleCandidate candidate, ScheduleWriter state, List<CandidateItem> items, int start, int stage, bool profiled)
	{
		for (var i = start; i < items.Count; i++)
		{
			var item = items[i];
			var guard = Guard(candidate, state, item);

			if (item.IsScope)
			{
				if (!state.ScopeCalls.TryGetValue(item, out var calls)) state.ScopeCalls[item] = calls = ScopeCalls(candidate, state, item);
				var (begin, end) = calls;
				w.WriteLine($"// {item.Order.ToString(CultureInfo.InvariantCulture)} {item.Name} ... {item.System!.Name}.{item.Step!.EndMethod!.Name}");
				var span = profiled ? Span(state, item) : null;
				if (span is not null)
				{
					// The scope's span covers its begin, everything inside it and its end.
					var condition = guard.Length == 0 ? ProfilingEnabled : $"{ProfilingEnabled} && {GuardName(item)}";
					w.WriteLine($"long {span.Value.Local} = {condition} ? _prof.Begin({span.Value.Field}) : 0L;");
				}

				w.WriteLine(guard + begin + ";");
				w.WriteLine("try");
				w.OpenBlock();
				WriteItems(w, candidate, state, items, i + 1, stage, profiled);
				w.CloseBlock();
				w.WriteLine("finally");
				w.OpenBlock();
				w.WriteLine(guard + end + ";");
				if (span is not null) w.WriteLine($"if ({ProfilingEnabled}) _prof.End({span.Value.Field}, {span.Value.Local});");
				w.CloseBlock();
				return;
			}

			if (item.Wraps)
			{
				var continuation = $"{KnownSymbols.StageName(stage)}_{state.ContinuationMethods.Count.ToString(CultureInfo.InvariantCulture)}";
				var next = "_next_" + continuation;
				state.Fields.Add($"private readonly global::Ion.GameLoopDelegate {next};");
				state.Continuations.Add($"{next} = new global::Ion.GameLoopDelegate({continuation});");
				state.ContinuationMethods.Add((continuation, items, i + 1, stage));

				var call = MiddlewareCall(candidate, state, item, next);
				w.WriteLine($"// {item.Order.ToString(CultureInfo.InvariantCulture)} {item.Name} (legacy middleware, wraps the rest of the stage)");
				if (guard.Length == 0) w.WriteLine(call + ";");
				else w.WriteLine($"{guard}{call}; else {continuation}(dt);");
				return;
			}

			if (!state.LeafCalls.TryGetValue(item, out var leaf)) state.LeafCalls[item] = leaf = LeafCall(candidate, state, item);
			var comment = $" // {item.Order.ToString(CultureInfo.InvariantCulture)} {item.Name}{(item.KindCode == "F" ? " (function)" : "")}";
			var leafSpan = profiled ? Span(state, item) : null;
			if (leafSpan is null)
			{
				w.WriteLine($"{guard}{leaf};{comment}");
				continue;
			}

			// A span per step: two timestamps when the profiler is active, two field reads when it is not, and nothing at all
			// when the Ion.Metrics.Profiling feature switch is off (the constant folds and the compiler drops both lines).
			if (guard.Length > 0) w.WriteLine(guard.TrimEnd());
			w.OpenBlock();
			w.WriteLine($"long {leafSpan.Value.Local} = {ProfilingEnabled} ? _prof.Begin({leafSpan.Value.Field}) : 0L;");
			w.WriteLine($"{leaf};{comment}");
			w.WriteLine($"if ({ProfilingEnabled}) _prof.End({leafSpan.Value.Field}, {leafSpan.Value.Local});");
			w.CloseBlock();
		}
	}

	/// <summary>The span id field (registered in the constructor with the item's name) and the timestamp local of an item.</summary>
	private (string Field, string Local)? Span(ScheduleWriter state, CandidateItem item)
	{
		if (!_profiling) return null;
		if (state.SpanFields.TryGetValue(item, out var existing)) return existing;

		EnsureProfilerField(state);
		var n = (state.Spans++).ToString(CultureInfo.InvariantCulture);
		state.Fields.Add($"private readonly global::Ion.SpanId _span{n};");
		state.Init.Add($"_span{n} = global::Ion.MetricsIds.Register({Literal(item.Name)});");
		return state.SpanFields[item] = ($"_span{n}", $"t{n}");
	}

	private static void EnsureProfilerField(ScheduleWriter state)
	{
		if (state.Fields.Contains(ProfilerField)) return;
		state.Fields.Add(ProfilerField);
		state.Init.Add("_prof = context.Profiler;");
	}

	private const string ProfilerField = "private readonly global::Ion.FrameProfiler _prof;";

	private static string GuardName(CandidateItem item) => "_g" + item.Entry.ToString(CultureInfo.InvariantCulture);

	private static string Guard(ScheduleCandidate candidate, ScheduleWriter state, CandidateItem item)
	{
		if (!candidate.Entries[item.Entry].Conditional) return "";
		var name = "_g" + item.Entry.ToString(CultureInfo.InvariantCulture);
		if (state.Guards.Add(item.Entry))
		{
			state.Fields.Add($"private readonly bool {name};");
			state.Init.Add($"{name} = context.IsActive({item.Entry.ToString(CultureInfo.InvariantCulture)});");
		}

		return $"if ({name}) ";
	}

	private bool IsDirect(CandidateItem item, IMethodSymbol method) =>
		item.System is { } system
		&& registrations.IsAccessible(system.Implementation)
		&& method.DeclaredAccessibility == Accessibility.Public
		&& method.Parameters.All(p => registrations.IsAccessible(p.Type));

	private string Instance(ScheduleWriter state, CandidateItem item)
	{
		var name = "_s" + item.Entry.ToString(CultureInfo.InvariantCulture);
		if (state.Instances.Add(item.Entry))
		{
			var type = Type(item.System!.Implementation);
			state.Fields.Add($"private readonly {type} {name};");
			state.Init.Add($"{name} = context.System<{type}>({item.Entry.ToString(CultureInfo.InvariantCulture)});");
		}

		return name;
	}

	private string DirectCall(ScheduleWriter state, CandidateItem item, IMethodSymbol method, string prefix, string? next = null)
	{
		var arguments = new List<string>();
		var p = 0;
		foreach (var parameter in method.Parameters)
		{
			if (KnownSymbols.Is(parameter.Type, known.GameTime))
			{
				arguments.Add("dt");
				continue;
			}

			if (KnownSymbols.Is(parameter.Type, known.GameLoopDelegate))
			{
				arguments.Add(next!);
				continue;
			}

			var field = $"_{prefix}{state.Items.ToString(CultureInfo.InvariantCulture)}_{p.ToString(CultureInfo.InvariantCulture)}";
			var type = Type(parameter.Type);
			state.Fields.Add($"private readonly {type} {field};");
			state.Init.Add($"{field} = context.Service<{type}>({item.Entry.ToString(CultureInfo.InvariantCulture)});");
			arguments.Add(field);
			p++;
		}

		var target = method.IsStatic ? Type(method.ContainingType) : Instance(state, item);
		return $"{target}.{method.Name}({string.Join(", ", arguments)})";
	}

	private string LeafCall(ScheduleCandidate candidate, ScheduleWriter state, CandidateItem item)
	{
		var n = (state.Items++).ToString(CultureInfo.InvariantCulture);
		var entry = item.Entry.ToString(CultureInfo.InvariantCulture);

		if (item.KindCode == "F")
		{
			var op = item.Op;
			var field = "_f" + n;
			if (op.DelegateType is { } delegateType && registrations.IsAccessible(delegateType))
			{
				state.Fields.Add($"private readonly {Type(delegateType)} {field};");
				state.Init.Add($"{field} = context.Function<{Type(delegateType)}>({entry});");
				var arguments = new List<string> { "dt" };
				for (var p = 0; p < op.Services.Count; p++)
				{
					var service = $"{field}_{p.ToString(CultureInfo.InvariantCulture)}";
					state.Fields.Add($"private readonly {Type(op.Services[p])} {service};");
					state.Init.Add($"{service} = context.Service<{Type(op.Services[p])}>({entry});");
					arguments.Add(service);
				}

				return $"{field}({string.Join(", ", arguments)})";
			}

			state.Fields.Add($"private readonly global::Ion.GameLoopDelegate {field};");
			state.Init.Add($"{field} = context.BoundFunction({entry});");
			return $"{field}(dt)";
		}

		var method = item.Step!.Method;
		if (item.Step.Query is { } query && item.System is { } querySystem && registrations.IsAccessible(querySystem.Implementation))
		{
			var world = $"_p{n}_0";
			state.Fields.Add($"private readonly {Type(known.ArchWorld!)} {world};");
			state.Init.Add($"{world} = context.Service<{Type(known.ArchWorld!)}>({entry});");
			var queryArguments = "dt, " + world;
			if (query.UsesCommands)
			{
				var commands = $"_p{n}_1";
				state.Fields.Add($"private readonly {Type(known.Commands!)} {commands};");
				state.Init.Add($"{commands} = context.Service<{Type(known.Commands!)}>({entry});");
				queryArguments += ", " + commands;
			}

			var queryTarget = query.Method.IsStatic ? Type(query.Method.ContainingType) : Instance(state, item);
			return $"{queryTarget}.{query.CompanionName}({queryArguments})";
		}

		if (IsDirect(item, method)) return DirectCall(state, item, method, "p");

		var bound = "_d" + n;
		state.Fields.Add($"private readonly global::Ion.GameLoopDelegate {bound};");
		state.Init.Add($"{bound} = context.Step({entry}, global::Ion.Stage.{KnownSymbols.StageName(item.Stage)}, {Literal(item.Step.Name)}, {item.Declaration.ToString(CultureInfo.InvariantCulture)});");
		return $"{bound}(dt)";
	}

	private (string Begin, string End) ScopeCalls(ScheduleCandidate candidate, ScheduleWriter state, CandidateItem item)
	{
		var n = (state.Items++).ToString(CultureInfo.InvariantCulture);
		var entry = item.Entry.ToString(CultureInfo.InvariantCulture);
		var begin = item.Step!.Method;
		var end = item.Step.EndMethod!;

		if (IsDirect(item, begin) && IsDirect(item, end)) return (DirectCall(state, item, begin, "b"), DirectCall(state, item, end, "e"));

		var stage = $"global::Ion.Stage.{KnownSymbols.StageName(item.Stage)}";
		var declaration = item.Declaration.ToString(CultureInfo.InvariantCulture);
		state.Fields.Add($"private readonly global::Ion.GameLoopDelegate _b{n};");
		state.Fields.Add($"private readonly global::Ion.GameLoopDelegate _e{n};");
		state.Init.Add($"_b{n} = context.ScopeBegin({entry}, {stage}, {Literal(begin.Name)}, {declaration});");
		state.Init.Add($"_e{n} = context.ScopeEnd({entry}, {stage}, {Literal(begin.Name)}, {declaration});");
		return ($"_b{n}(dt)", $"_e{n}(dt)");
	}

	private string MiddlewareCall(ScheduleCandidate candidate, ScheduleWriter state, CandidateItem item, string next)
	{
		var n = (state.Items++).ToString(CultureInfo.InvariantCulture);
		var entry = item.Entry.ToString(CultureInfo.InvariantCulture);
		var conditional = candidate.Entries[item.Entry].Conditional;
		var field = "_m" + n;

		string Create(string factory) => conditional ? $"{field} = context.IsActive({entry}) ? {factory} : null!;" : $"{field} = {factory};";

		if (item.KindCode == "D")
		{
			state.Fields.Add($"private readonly global::Ion.GameLoopDelegate {field};");
			state.AddMiddleware(Create($"context.Middleware({entry})({next})"));
			return $"{field}(dt)";
		}

		var method = item.Step!.Method;
		if (IsDirect(item, method))
		{
			if (item.Step.Signature == SignatureKind.LegacyVoidNext) return DirectCall(state, item, method, "p", next);

			var target = method.IsStatic ? Type(method.ContainingType) : Instance(state, item);
			state.Fields.Add($"private readonly global::Ion.GameLoopDelegate {field};");
			state.AddMiddleware(Create($"{target}.{method.Name}({next})"));
			return $"{field}(dt)";
		}

		state.Fields.Add($"private readonly global::Ion.GameLoopDelegate {field};");
		state.AddMiddleware(Create($"context.StepMiddleware({entry}, global::Ion.Stage.{KnownSymbols.StageName(item.Stage)}, {Literal(method.Name)}, {item.Declaration.ToString(CultureInfo.InvariantCulture)})({next})"));
		return $"{field}(dt)";
	}

	#endregion

	private static string Type(ITypeSymbol type) => type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString(TypeFormat);

	private static string Resolve(ITypeSymbol type, string services) =>
		$"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{Type(type)}>({services})";

	private static string TypeArray(IReadOnlyCollection<ITypeSymbol> types) =>
		types.Count == 0 ? "global::System.Type.EmptyTypes" : $"new global::System.Type[] {{ {string.Join(", ", types.Select(t => $"typeof({Type(t)})"))} }}";

	private static string NullableTypeArray(IReadOnlyCollection<ITypeSymbol>? types) => types is null ? "null" : TypeArray(types);

	private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

	private static string Identifier(string name) => SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

	private static string Escape(string value) => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
