using System.Globalization;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ion.Generators;

/// <summary>
/// Writes <c>IonEvents.g.cs</c>: the <c>EventUsage</c> summary of this assembly and, for an application, the closed
/// <c>GeneratedEventBus</c> (one typed channel field per event type, compile-time ids, usage-based capacities), the
/// interceptor of <c>IonApplication.CreateBuilder</c> that installs it, and interceptors that route this assembly's
/// <c>Emit</c>/<c>Reader</c> calls straight to the typed fields.
/// </summary>
internal sealed class EventBusEmitter(KnownSymbols known, EventAnalyzer events)
{
	private const string GeneratorName = "Ion.Generators";
	private const string GeneratorVersion = "0.3.0";
	private const string Unsafe = "global::System.Runtime.CompilerServices.Unsafe";

	private readonly Compilation _compilation = known.Compilation;

	/// <summary>Writes the file, or returns null when there is nothing to write.</summary>
	public string? Emit(bool canIntercept, CancellationToken cancellationToken)
	{
		var summaries = events.Types.Where(t => t.Own != 0 && IsAccessible(t.Type)).ToList();

		// The closed bus: only for an application (it creates the builder) with event calls of its own.
		var busTypes = new List<EventTypeUsage>();
		var createBuilders = new List<(string Attribute, IMethodSymbol Method, InvocationExpressionSyntax Invocation)>();
		if (canIntercept && events.CreateBuilderCalls.Count > 0 && events.HasOwnSites && known.IonApplicationBuilder is not null)
		{
			busTypes = events.Types.Where(t => IsAccessible(t.Type)).ToList();
			foreach (var (invocation, model, method) in events.CreateBuilderCalls)
			{
				if (InterceptableLocations.AttributeFor(model, invocation, cancellationToken) is { } attribute) createBuilders.Add((attribute, method, invocation));
			}

			if (createBuilders.Count == 0) busTypes.Clear();
		}

		if (summaries.Count == 0 && busTypes.Count == 0) return null;

		var ids = new Dictionary<ITypeSymbol, int>(SymbolEqualityComparer.Default);
		for (var i = 0; i < busTypes.Count; i++) ids[busTypes[i].Type] = i + 1;

		// The Emit/Reader calls of this assembly on a type of the bus.
		var routed = new List<EventSite>();
		foreach (var usage in busTypes)
		{
			foreach (var site in usage.Sites)
			{
				if (site.Api == EventApi.None) continue;
				if (InterceptableLocations.AttributeFor(site.Model, site.Invocation, cancellationToken) is not { } attribute) continue;
				site.Attribute = attribute;
				routed.Add(site);
			}
		}

		routed = [.. routed.OrderBy(s => s.Invocation.SyntaxTree.FilePath, StringComparer.Ordinal).ThenBy(s => s.Invocation.SpanStart)];
		for (var i = 0; i < routed.Count; i++) routed[i].Index = i;

		var w = new SourceWriter();
		w.WriteLine("// <auto-generated/>");
		w.WriteLine("// Generated by the Ion event generator (Ion.Generators). Do not edit.");
		w.WriteLine("#nullable enable");
		w.WriteLine("// The interceptors of Emit take 'in' parameters without the modreq(InAttribute) of the interface method they intercept.");
		w.WriteLine("#pragma warning disable CS9154");
		w.WriteEmptyLines(1);

		foreach (var usage in summaries)
		{
			w.WriteLine($"[assembly: global::Ion.EventUsageAttribute(typeof({Type(usage.Type)}), (global::Ion.EventUsage){usage.Own.ToString(CultureInfo.InvariantCulture)})] // {EventAnalyzer.DescribeUsage(usage.Own)}");
		}

		if (busTypes.Count > 0)
		{
			if (summaries.Count > 0) w.WriteEmptyLines(1);
			WriteInterceptsLocationAttribute(w);
			w.WriteLine("namespace Ion.Generated");
			w.OpenBlock();
			WriteBus(w, busTypes, ids);
			w.WriteEmptyLines(1);
			WriteInterceptors(w, createBuilders, routed, ids);
			w.CloseBlock();
		}

		return w.ToString().Replace("\n\n}", "\n}").TrimEnd('\n') + "\n";
	}

	private static void WriteTypeAttributes(SourceWriter w)
	{
		w.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{GeneratorName}\", \"{GeneratorVersion}\")]");
		w.WriteLine("[global::System.Diagnostics.DebuggerNonUserCode]");
		w.WriteLine("[global::System.Diagnostics.StackTraceHidden]");
		w.WriteLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
	}

	private static void WriteInterceptsLocationAttribute(SourceWriter w)
	{
		w.WriteLine("namespace System.Runtime.CompilerServices");
		w.OpenBlock();
		w.WriteLine("[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
		w.WriteLine("file sealed class InterceptsLocationAttribute : global::System.Attribute");
		w.OpenBlock();
		w.WriteLine("public InterceptsLocationAttribute(int version, string data)");
		w.OpenBlock();
		w.WriteLine("_ = version;");
		w.WriteLine("_ = data;");
		w.CloseBlock();
		w.CloseBlock();
		w.CloseBlock();
		w.WriteEmptyLines(1);
	}

	private static void WriteBus(SourceWriter w, List<EventTypeUsage> types, Dictionary<ITypeSymbol, int> ids)
	{
		w.WriteLine("/// <summary>");
		w.WriteLine("/// The event bus of this application: one typed channel per event type it (or an Ion assembly it references) uses,");
		w.WriteLine("/// with compile-time ids. Types it does not list get a channel from the runtime bus on first use.");
		w.WriteLine("/// </summary>");
		WriteTypeAttributes(w);
		w.WriteLine("file sealed class GeneratedEventBus : global::Ion.EventBus, global::Ion.IEvents");
		w.OpenBlock();

		foreach (var usage in types)
		{
			var id = ids[usage.Type].ToString(CultureInfo.InvariantCulture);
			w.WriteLine($"/// <summary>Id {id}: <c>{Escape(EventAnalyzer.Display(usage.Type))}</c> ({EventAnalyzer.DescribeUsage(usage.All)}).</summary>");
			w.WriteLine($"public readonly global::Ion.EventChannel<{Type(usage.Type)}> E{id};");
		}

		w.WriteEmptyLines(1);
		w.WriteLine("private static bool _idsAssigned;");
		w.WriteEmptyLines(1);
		w.WriteLine("public GeneratedEventBus(global::Ion.ILoopContext? loop) : base(loop)");
		w.OpenBlock();
		w.WriteLine("AssignIds();");
		foreach (var usage in types)
		{
			var id = ids[usage.Type].ToString(CultureInfo.InvariantCulture);
			w.WriteLine($"E{id} = Register<{Type(usage.Type)}>({EventAnalyzer.Capacity(usage.All).ToString(CultureInfo.InvariantCulture)});");
		}

		w.CloseBlock();
		w.WriteEmptyLines(1);

		w.WriteLine("/// <summary>Gives every event type of this bus its compile-time id (<see cref=\"global::Ion.EventId{T}\"/>).</summary>");
		w.WriteLine("public static void AssignIds()");
		w.OpenBlock();
		w.WriteLine("if (_idsAssigned) return;");
		w.WriteLine("_idsAssigned = true;");
		foreach (var usage in types)
		{
			w.WriteLine($"global::Ion.EventId<{Type(usage.Type)}>.TryAssign({ids[usage.Type].ToString(CultureInfo.InvariantCulture)});");
		}

		w.CloseBlock();
		w.WriteEmptyLines(1);

		w.WriteLine("/// <summary>Installs this bus on <paramref name=\"builder\"/>.</summary>");
		w.WriteLine("public static global::Ion.IonApplicationBuilder Install(global::Ion.IonApplicationBuilder builder)");
		w.OpenBlock();
		w.WriteLine("AssignIds();");
		w.WriteLine("return builder.UseEventBus(static loop => new GeneratedEventBus(loop));");
		w.CloseBlock();
		w.WriteEmptyLines(1);

		// IEvents, re-implemented: the typeof tests fold away for each (value type) T, leaving a field access.
		w.WriteLine("void global::Ion.IEvents.Emit<T>(in T e)");
		w.OpenBlock();
		foreach (var usage in types)
		{
			var type = Type(usage.Type);
			var id = ids[usage.Type].ToString(CultureInfo.InvariantCulture);
			w.WriteLine($"if (typeof(T) == typeof({type})) {{ E{id}.Emit(in {Unsafe}.As<T, {type}>(ref {Unsafe}.AsRef(in e))); return; }}");
		}

		w.WriteLine("Emit(in e);");
		w.CloseBlock();
		w.WriteEmptyLines(1);

		w.WriteLine("global::Ion.EventReader<T> global::Ion.IEvents.Reader<T>()");
		w.OpenBlock();
		foreach (var usage in types)
		{
			var type = Type(usage.Type);
			var id = ids[usage.Type].ToString(CultureInfo.InvariantCulture);
			w.WriteLine($"if (typeof(T) == typeof({type})) {{ var reader = E{id}.Reader(); return {Unsafe}.As<global::Ion.EventReader<{type}>, global::Ion.EventReader<T>>(ref reader); }}");
		}

		w.WriteLine("return Reader<T>();");
		w.CloseBlock();
		w.CloseBlock();
	}

	private void WriteInterceptors(SourceWriter w, List<(string Attribute, IMethodSymbol Method, InvocationExpressionSyntax Invocation)> createBuilders, List<EventSite> routed, Dictionary<ITypeSymbol, int> ids)
	{
		w.WriteLine("/// <summary>Installs the generated event bus, and routes this assembly's event calls to its typed channels.</summary>");
		WriteTypeAttributes(w);
		w.WriteLine("file static class IonEventInterceptors");
		w.OpenBlock();

		var first = true;
		for (var i = 0; i < createBuilders.Count; i++)
		{
			var (attribute, method, invocation) = createBuilders[i];
			if (!first) w.WriteEmptyLines(1);
			first = false;

			w.WriteLine($"// {Where(invocation)}: CreateBuilder, installs the generated event bus");
			w.WriteLine($"[{attribute}]");
			var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {Identifier(p.Name)}"));
			var arguments = string.Join(", ", method.Parameters.Select(p => Identifier(p.Name)));
			w.WriteLine($"public static {Type(method.ReturnType)} CreateBuilder_{i.ToString(CultureInfo.InvariantCulture)}({parameters}) =>");
			w.WriteLine($"\tGeneratedEventBus.Install({Type(method.ContainingType)}.CreateBuilder({arguments}));");
		}

		foreach (var site in routed)
		{
			if (!first) w.WriteEmptyLines(1);
			first = false;

			var type = Type(site.Type);
			var field = "E" + ids[site.Type].ToString(CultureInfo.InvariantCulture);
			var index = site.Index.ToString(CultureInfo.InvariantCulture);
			w.WriteLine($"// {Where(site.Invocation)}: {(site.Kind == EventSiteKind.Emit ? "Emit" : "Reader")}<{Escape(EventAnalyzer.Display(site.Type))}>");
			w.WriteLine($"[{site.Attribute}]");
			w.WriteLine("[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");

			switch (site.Api)
			{
				case EventApi.EventsEmit:
				case EventApi.BusEmit:
				{
					var receiver = site.Api == EventApi.EventsEmit ? "global::Ion.IEvents" : "global::Ion.EventBus";
					w.WriteLine($"public static void Emit_{index}(this {receiver} receiver, in {type} e)");
					w.OpenBlock();
					w.WriteLine($"if (receiver is GeneratedEventBus bus) bus.{field}.Emit(in e);");
					w.WriteLine("else receiver.Emit(in e);");
					w.CloseBlock();
					break;
				}

				case EventApi.ExtensionEmit:
					w.WriteLine($"public static void Emit_{index}(this global::Ion.IEvents events)");
					w.OpenBlock();
					w.WriteLine($"if (events is GeneratedEventBus bus) bus.{field}.Emit(default({type}));");
					w.WriteLine($"else global::Ion.EventsExtensions.Emit<{type}>(events);");
					w.CloseBlock();
					break;

				case EventApi.EventsReader:
				case EventApi.BusReader:
				{
					var receiver = site.Api == EventApi.EventsReader ? "global::Ion.IEvents" : "global::Ion.EventBus";
					w.WriteLine($"public static global::Ion.EventReader<{type}> Reader_{index}(this {receiver} receiver) =>");
					w.WriteLine($"\treceiver is GeneratedEventBus bus ? bus.{field}.Reader() : receiver.Reader<{type}>();");
					break;
				}
			}
		}

		w.CloseBlock();
	}

	private static string Where(InvocationExpressionSyntax invocation)
	{
		var span = invocation.GetLocation().GetLineSpan();
		return $"{System.IO.Path.GetFileName(span.Path)}({(span.StartLinePosition.Line + 1).ToString(CultureInfo.InvariantCulture)},{(span.StartLinePosition.Character + 1).ToString(CultureInfo.InvariantCulture)})";
	}

	private bool IsAccessible(ITypeSymbol type)
	{
		switch (type)
		{
			case IArrayTypeSymbol:
			case ITypeParameterSymbol:
			case IErrorTypeSymbol:
			case IPointerTypeSymbol:
				return false;
			case INamedTypeSymbol named:
				if (named.IsAnonymousType || named.IsUnboundGenericType) return false;
				for (var t = named; t is not null; t = t.ContainingType)
				{
					if (t.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is BaseTypeDeclarationSyntax declaration && declaration.Modifiers.Any(m => m.IsKind(SyntaxKind.FileKeyword)))) return false;
				}

				if (!_compilation.IsSymbolAccessibleWithin(named, _compilation.Assembly)) return false;
				return named.TypeArguments.All(IsAccessible);
			default:
				return false;
		}
	}

	private static string Type(ITypeSymbol type) => type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

	private static string Identifier(string name) => SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

	private static string Escape(string value) => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
