using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ion.Generators;

/// <summary>
/// Makes the <c>Program</c> class of an Ion game written with top-level statements public (<c>public partial class
/// Program</c>), so its tests can name it: <c>IonTestHost.UseEntryPoint&lt;Program&gt;()</c> runs that entry point (the
/// same convention as ASP.NET Core's <c>WebApplicationFactory&lt;Program&gt;</c>). Nothing is emitted when the program
/// declares <c>Program</c> itself with an accessibility, or when its top-level statements do not create an Ion application.
/// </summary>
internal static class PublicProgram
{
	public const string HintName = "IonProgram.g.cs";

	/// <summary>A file with top-level statements that call <c>CreateBuilder</c> (the cheap syntactic filter).</summary>
	public static bool IsCandidate(SyntaxNode node) =>
		node is CompilationUnitSyntax unit
		&& unit.Members.OfType<GlobalStatementSyntax>().Any(statement => statement.DescendantNodes().OfType<InvocationExpressionSyntax>().Any(IsCreateBuilder));

	/// <summary>Whether the compilation's top-level <c>Program</c> should be declared public.</summary>
	public static bool ShouldEmit(Compilation compilation, CancellationToken cancellationToken)
	{
		if (compilation.GetTypeByMetadataName("Ion.IonApplication") is null) return false;
		if (compilation.GetTypeByMetadataName("Program") is not { } program || program.DeclaredAccessibility == Accessibility.Public) return false;

		foreach (var reference in program.DeclaringSyntaxReferences)
		{
			cancellationToken.ThrowIfCancellationRequested();

			// The program declares the class itself: keep what it says.
			if (reference.GetSyntax(cancellationToken) is TypeDeclarationSyntax declaration && declaration.Modifiers.Any(IsAccessibility)) return false;
		}

		return true;
	}

	public const string Source = """
		// <auto-generated/>
		// The Ion generator declares the Program class of top-level statements public, so tests can run this entry point:
		// IonTestHost.UseEntryPoint<Program>() in Ion.Testing.

		/// <summary>The game's entry point (its top-level statements).</summary>
		public partial class Program
		{
		}

		""";

	private static bool IsCreateBuilder(InvocationExpressionSyntax invocation) => invocation.Expression switch
	{
		MemberAccessExpressionSyntax member => member.Name.Identifier.ValueText == "CreateBuilder",
		SimpleNameSyntax simple => simple.Identifier.ValueText == "CreateBuilder",
		_ => false,
	};

	private static bool IsAccessibility(SyntaxToken modifier) =>
		modifier.IsKind(SyntaxKind.PublicKeyword) || modifier.IsKind(SyntaxKind.InternalKeyword) || modifier.IsKind(SyntaxKind.PrivateKeyword)
		|| modifier.IsKind(SyntaxKind.ProtectedKeyword) || modifier.IsKind(SyntaxKind.FileKeyword);
}
