using System.Globalization;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ion.Generators;

/// <summary>
/// Expands the <c>[Query]</c> methods of the compilation (<c>IonQueries.g.cs</c>): for each, a public method on the same
/// partial type, <c>__IonQuery_{Method}(GameTime dt, World world[, Commands commands])</c>, that loops over Arch's chunks
/// with <c>GetFirst</c>/<c>Unsafe.Add</c> (the chunk-span form measured fastest in roadmap 5.7), calls the method per
/// entity in Arch's own order (archetypes and chunks in order, entities from last to first within a chunk, as
/// <c>World.Query</c> does) and checks after each call that the world's structure did not change. It carries the original's stage and
/// ordering attributes and <c>[ExpandedStep]</c>, so the schedule (generated or reflection-bound) runs it in the
/// original's place, under the original's name. A module initializer registers every query component with Arch
/// (<c>EcsComponents.Register</c>), which NativeAOT needs.
/// </summary>
internal sealed class QueryEmitter(KnownSymbols known, QueryAnalyzer queries)
{
	private const string GeneratorName = "Ion.Generators";
	private const string GeneratorVersion = "0.3.0";
	private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat;

	/// <summary>The <c>[Query]</c> methods declared in the compilation's source, in syntax order.</summary>
	public List<IMethodSymbol> FindQueries(CancellationToken cancellationToken)
	{
		var result = new List<IMethodSymbol>();
		var seen = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
		foreach (var tree in known.Compilation.SyntaxTrees)
		{
			var root = tree.GetRoot(cancellationToken);
			SemanticModel? model = null;
			foreach (var declaration in root.DescendantNodes().OfType<MethodDeclarationSyntax>())
			{
				if (!declaration.AttributeLists.SelectMany(l => l.Attributes).Any(a => IsQueryName(a.Name.ToString()))) continue;
				model ??= known.Compilation.GetSemanticModel(tree);
				if (model.GetDeclaredSymbol(declaration, cancellationToken) is IMethodSymbol method && queries.IsQuery(method) && seen.Add(method)) result.Add(method);
			}
		}

		return result;
	}

	public static bool IsQueryName(string name) => name is "Query" or "QueryAttribute" || name.EndsWith(".Query", StringComparison.Ordinal) || name.EndsWith(".QueryAttribute", StringComparison.Ordinal);

	public string? Emit(List<IMethodSymbol> methods, CancellationToken cancellationToken)
	{
		var valid = methods.Select(m => queries.Analyze(m, cancellationToken)).Where(q => q is not null).Cast<QueryInfo>().ToList();
		if (valid.Count == 0) return null;

		var w = new SourceWriter();
		w.WriteLine("// <auto-generated/>");
		w.WriteLine("// Generated by the Ion schedule generator (Ion.Generators): [Query] methods expanded into chunk loops. Do not edit.");
		w.WriteLine("#nullable enable");
		w.WriteLine("#pragma warning disable CS0618, CS1591, CA2255");
		w.WriteEmptyLines(1);

		foreach (var group in valid.GroupBy(q => q.Method.ContainingType, SymbolEqualityComparer.Default))
		{
			var type = (INamedTypeSymbol)group.Key!;
			var chain = new List<INamedTypeSymbol>();
			for (var t = type; t is not null; t = t.ContainingType) chain.Insert(0, t);

			var ns = type.ContainingNamespace is { IsGlobalNamespace: false } n ? n.ToDisplayString() : null;
			if (ns is not null)
			{
				w.WriteLine($"namespace {ns}");
				w.OpenBlock();
			}

			foreach (var t in chain)
			{
				w.WriteLine($"partial {Kind(t)} {TypeDeclarationName(t)}");
				w.OpenBlock();
			}

			var first = true;
			foreach (var query in group)
			{
				if (!first) w.WriteEmptyLines(1);
				first = false;
				WriteQuery(w, query);
			}

			foreach (var _ in chain) w.CloseBlock();
			if (ns is not null) w.CloseBlock();
			w.WriteEmptyLines(1);
		}

		WriteRegistrations(w, valid);
		return w.ToString().Replace("\n\n}", "\n}").TrimEnd('\n') + "\n";
	}

	private void WriteQuery(SourceWriter w, QueryInfo query)
	{
		var method = query.Method;
		var companion = query.CompanionName;
		var description = companion + "_Description";
		var stepName = method.ContainingType.MetadataName + "." + method.Name;

		w.WriteLine($"private static readonly global::Arch.Core.QueryDescription {description} = new global::Arch.Core.QueryDescription(");
		w.OpenIndent();
		w.WriteLine($"all: {Signature(query.All)},");
		w.WriteLine($"any: {(query.Any.Count == 0 ? "null" : Signature(query.Any))},");
		w.WriteLine($"none: {(query.None.Count == 0 ? "null" : Signature(query.None))});");
		w.CloseIndent();
		w.WriteEmptyLines(1);

		w.WriteLine($"/// <summary>Runs <see cref=\"{Escape(method.Name)}\"/> for every matching entity of <paramref name=\"world\"/> (generated from its [Query]).</summary>");
		w.WriteLine($"[global::Ion.ExpandedStep({Literal(method.Name)})]");
		foreach (var attribute in CopiedAttributes(method)) w.WriteLine($"[{attribute}]");
		w.WriteLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
		w.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{GeneratorName}\", \"{GeneratorVersion}\")]");
		w.WriteLine("[global::System.Diagnostics.DebuggerNonUserCode]");
		w.WriteLine("[global::System.Diagnostics.StackTraceHidden]");
		var parameters = "global::Ion.GameTime dt, global::Arch.Core.World world" + (query.UsesCommands ? ", global::Ion.Extensions.Ecs.Commands commands" : "");
		w.WriteLine($"public {(method.IsStatic ? "static " : "")}void {companion}({parameters})");
		w.OpenBlock();

		var usesDelta = query.Parameters.Any(p => p.Kind == QueryParameterKind.Delta);
		if (usesDelta) w.WriteLine("var __delta = dt.Delta;");
		w.WriteLine($"foreach (ref var __chunk in world.Query(in {description}))");
		w.OpenBlock();
		var usesEntity = !query.Unchecked || query.Parameters.Any(p => p.Kind == QueryParameterKind.Entity);
		w.WriteLine("var __count = __chunk.Count;");
		if (!query.Unchecked) w.WriteLine("var __size = world.Size;");
		if (usesEntity) w.WriteLine("ref var __entities = ref __chunk.Entity(0);");
		for (var c = 0; c < query.Components.Count; c++)
		{
			w.WriteLine($"ref var __c{c.ToString(CultureInfo.InvariantCulture)} = ref __chunk.GetFirst<{Type(query.Components[c])}>();");
		}

		w.WriteLine("for (var __i = __count - 1; __i >= 0; __i--)");
		w.OpenBlock();
		if (usesEntity) w.WriteLine("var __entity = global::System.Runtime.CompilerServices.Unsafe.Add(ref __entities, __i);");

		var arguments = new List<string>();
		foreach (var parameter in query.Parameters)
		{
			var prefix = parameter.RefKind switch
			{
				RefKind.Ref => "ref ",
				RefKind.In => "in ",
				_ => "",
			};

			var value = parameter.Kind switch
			{
				QueryParameterKind.Component => $"global::System.Runtime.CompilerServices.Unsafe.Add(ref __c{query.Components.FindIndex(t => SymbolEqualityComparer.Default.Equals(t, parameter.Type)).ToString(CultureInfo.InvariantCulture)}, __i)",
				QueryParameterKind.Entity => "__entity",
				QueryParameterKind.Delta => "__delta",
				QueryParameterKind.Time => "dt",
				QueryParameterKind.Commands => "commands",
				_ => "world",
			};

			// Locals and array elements can be passed by ref; the delta and dt only as in or by value.
			if (parameter.Kind is QueryParameterKind.Time or QueryParameterKind.Commands or QueryParameterKind.World && prefix == "ref ") prefix = "";
			arguments.Add(prefix + value);
		}

		w.WriteLine($"{method.Name}({string.Join(", ", arguments)});");
		if (!query.Unchecked) w.WriteLine($"if (__chunk.Count != __count || world.Size != __size) global::Ion.Extensions.Ecs.QueryGuard.ThrowStructuralChange({Literal(stepName)}, __entity);");
		w.CloseBlock();
		w.CloseBlock();
		w.CloseBlock();
	}

	private void WriteRegistrations(SourceWriter w, List<QueryInfo> queries)
	{
		if (known.EcsComponents is null) return;

		var types = new List<ITypeSymbol>();
		foreach (var query in queries)
		{
			foreach (var type in query.All.Concat(query.Any).Concat(query.None))
			{
				if (IsAccessible(type) && !types.Contains(type, SymbolEqualityComparer.Default)) types.Add(type);
			}
		}

		if (types.Count == 0) return;

		w.WriteLine("namespace Ion.Generated");
		w.OpenBlock();
		w.WriteLine("/// <summary>Registers the components of this assembly's [Query] methods with Arch (NativeAOT needs their arrays up front).</summary>");
		w.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{GeneratorName}\", \"{GeneratorVersion}\")]");
		w.WriteLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
		w.WriteLine("file static class IonQueryComponents");
		w.OpenBlock();
		w.WriteLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
		w.WriteLine("internal static void Register()");
		w.OpenBlock();
		foreach (var type in types) w.WriteLine($"global::Ion.Extensions.Ecs.EcsComponents.Register<{Type(type)}>();");
		w.CloseBlock();
		w.CloseBlock();
		w.CloseBlock();
	}

	private IEnumerable<string> CopiedAttributes(IMethodSymbol method)
	{
		foreach (var attribute in method.GetAttributes())
		{
			if (attribute.AttributeClass is not { } attributeClass) continue;

			if (known.StageAttributes.ContainsKey(attributeClass))
			{
				var order = attribute.NamedArguments.FirstOrDefault(a => a.Key == "Order").Value.Value;
				yield return order is int value
					? $"{Type(attributeClass)}(Order = {value.ToString(CultureInfo.InvariantCulture)})"
					: Type(attributeClass);
			}
			else if (KnownSymbols.Is(attributeClass, known.AfterAttribute) || KnownSymbols.Is(attributeClass, known.BeforeAttribute))
			{
				yield return Type(attributeClass);
			}
		}
	}

	private static string Signature(List<ITypeSymbol> types) =>
		types.Count == 0
			? "new global::Arch.Core.Signature()"
			: $"new global::Arch.Core.Signature({string.Join(", ", types.Select(t => $"global::Arch.Core.Component<{Type(t)}>.ComponentType"))})";

	private static bool IsAccessible(ITypeSymbol type)
	{
		for (var t = type; t is not null; t = t.ContainingType)
		{
			if (t.DeclaredAccessibility is Accessibility.Private or Accessibility.Protected or Accessibility.ProtectedAndInternal) return false;
		}

		return true;
	}

	private static string Kind(INamedTypeSymbol type) => type switch
	{
		{ IsRecord: true, IsValueType: true } => "record struct",
		{ IsRecord: true } => "record",
		{ IsValueType: true } => "struct",
		{ TypeKind: TypeKind.Interface } => "interface",
		_ => "class",
	};

	private static string TypeDeclarationName(INamedTypeSymbol type) =>
		type.TypeParameters.Length == 0 ? type.Name : $"{type.Name}<{string.Join(", ", type.TypeParameters.Select(p => p.Name))}>";

	private static string Type(ITypeSymbol type) => type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString(TypeFormat);

	private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

	private static string Escape(string value) => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
