using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Ion.Generators;

namespace Ion.Core.InternalGenerators;

/// <summary>
/// Emits the function step registrations (<c>app.Update((GameTime dt, IInputState input) =&gt; ...)</c>) for every stage
/// with zero to <see cref="MAX_SERVICES"/> injected services. In <c>Ion.Core.Abstractions</c> they extend
/// <c>IIonApplication</c>; in <c>Ion.Extensions.Scenes.Abstractions</c> they extend <c>ISceneBuilder</c>.
/// </summary>
[Generator]
public class StageStepExtensionsGenerator : IIncrementalGenerator
{
	private const int MAX_SERVICES = 4;
	private static readonly string[] STAGES = ["Init", "First", "FixedUpdate", "Update", "Render", "Last", "Destroy"];

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var assemblyName = context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName ?? "");

		context.RegisterSourceOutput(assemblyName, static (spc, name) =>
		{
			switch (name)
			{
				case "Ion.Core.Abstractions":
					spc.AddSource("StageStepExtensions.g.cs", _generate("Ion", "StageStepExtensions", "IIonApplication", "application"));
					break;
				case "Ion.Extensions.Scenes.Abstractions":
					spc.AddSource("SceneStageStepExtensions.g.cs", _generate("Ion.Extensions.Scenes", "SceneStageStepExtensions", "ISceneBuilder", "scene"));
					break;
			}
		});
	}

	private static SourceText _generate(string ns, string className, string receiver, string receiverDescription)
	{
		var source = new SourceWriter();
		source.WriteLine("// <auto-generated/>");
		source.WriteLine("#nullable enable");
		source.WriteLine("using Microsoft.Extensions.DependencyInjection;");
		source.WriteEmptyLines(1);
		source.WriteLine($"namespace {ns};");
		source.WriteEmptyLines(1);
		source.WriteLine("/// <summary>");
		source.WriteLine($"/// Function steps: delegates added to a stage of the {receiverDescription}'s schedule, with up to {MAX_SERVICES} injected services");
		source.WriteLine("/// resolved once when the schedule is built. They are ordered like system steps (by order, then registration order).");
		source.WriteLine("/// </summary>");
		source.WriteLine($"public static class {className}");
		source.OpenBlock();

		foreach (var stage in STAGES)
		{
			source.WriteLine($"#region {stage}");

			for (var count = 0; count <= MAX_SERVICES; count++)
			{
				var typeArgs = string.Join(", ", Enumerable.Range(0, count).Select(i => $"TService{i}"));
				var generic = count == 0 ? "" : $"<{typeArgs}>";
				var actionArgs = count == 0 ? "GameTime" : $"GameTime, {typeArgs}";
				var constraints = string.Join(" ", Enumerable.Range(0, count).Select(i => $"where TService{i} : notnull"));

				source.WriteLine("/// <summary>");
				source.WriteLine($"/// Adds <paramref name=\"step\"/> to the {stage} stage{(count == 0 ? "" : ", with its service parameters resolved once when the schedule is built")}.");
				source.WriteLine("/// </summary>");
				source.WriteLine("/// <param name=\"builder\">The schedule to add to.</param>");
				source.WriteLine("/// <param name=\"step\">The step. Attributes <c>[Before&lt;T&gt;]</c>/<c>[After&lt;T&gt;]</c> on it (or on the lambda) are honoured.</param>");
				source.WriteLine("/// <param name=\"order\">The step order; see <see cref=\"Ion.StageOrder\"/>.</param>");
				source.WriteLine("/// <param name=\"name\">The name printed by the schedule; derived from the delegate when null.</param>");
				source.WriteLine($"public static {receiver} {stage}{generic}(this {receiver} builder, global::System.Action<{actionArgs}> step, int order = global::Ion.StageOrder.Default, string? name = null){(constraints.Length > 0 ? " " + constraints : "")}");
				source.OpenBlock();

				if (count == 0)
				{
					source.WriteLine($"var direct = global::Ion.ScheduleModel.AsGameLoopDelegate(step);");
					source.WriteLine($"builder.Schedule.AddFunction(global::Ion.Stage.{stage}, step, global::System.Type.EmptyTypes, _ => direct, order, name);");
				}
				else
				{
					var types = string.Join(", ", Enumerable.Range(0, count).Select(i => $"typeof(TService{i})"));
					source.WriteLine($"builder.Schedule.AddFunction(global::Ion.Stage.{stage}, step, new global::System.Type[] {{ {types} }}, services =>");
					source.OpenBlock();
					for (var i = 0; i < count; i++) source.WriteLine($"var service{i} = services.GetRequiredService<TService{i}>();");
					source.WriteLine($"return dt => step(dt, {string.Join(", ", Enumerable.Range(0, count).Select(i => $"service{i}"))});");
					source.CloseBlock();
					source.WriteLine(", order, name);");
				}

				source.WriteLine("return builder;");
				source.CloseBlock();
				source.WriteEmptyLines(1);
			}

			source.WriteLine("#endregion");
			source.WriteEmptyLines(1);
		}

		source.CloseAllBlocks();
		return source.ToSourceText();
	}
}
