// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLinksValidator from 'starlight-links-validator';

// Served from GitHub Pages at https://jimbuck.github.io/Ion/. Override with DOCS_SITE / DOCS_BASE for forks.
const site = process.env.DOCS_SITE ?? 'https://jimbuck.github.io';
const base = process.env.DOCS_BASE ?? '/Ion';

const section = (label, directory, collapsed = false) => ({ label, collapsed, items: [{ autogenerate: { directory } }] });
// Sections with nested groups list their top-level pages explicitly so the nested group gets a real label
// (an autogenerated subdirectory is labelled with its folder name).
const pages = (directory, slugs) => slugs.map((slug) => `${directory}/${slug}`);
const nested = (label, directory, top, groups) => ({
	label,
	items: [...pages(directory, top), ...groups.map(([groupLabel, sub]) => section(groupLabel, `${directory}/${sub}`))],
});

export default defineConfig({
	site,
	base,
	integrations: [
		starlight({
			title: 'Ion',
			description: 'A performant, agent-friendly 2D/3D game engine for .NET built on systems and ECS.',
			logo: { src: './src/assets/logo-lockup.svg', replacesTitle: true, alt: 'Ion' },
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/jimbuck/Ion' }],
			editLink: { baseUrl: 'https://github.com/jimbuck/Ion/edit/main/website/' },
			lastUpdated: true,
			customCss: ['./src/styles/custom.css'],
			// Dark only: a fixed dark theme and no theme picker.
			components: {
				ThemeProvider: './src/components/ThemeProvider.astro',
				ThemeSelect: './src/components/ThemeSelect.astro',
			},
			expressiveCode: { themes: ['night-owl'], useStarlightUiThemeColors: true },
			// Pagefind full-text search over every page (Starlight's built-in integration).
			pagefind: true,
			plugins: [starlightLinksValidator({ errorOnRelativeLinks: false, errorOnLocalLinks: false })],
			sidebar: [
				section('Getting started', 'getting-started'),
				section('Core concepts', 'concepts'),
				nested('Rendering', 'rendering', ['overview', 'graphics-backends', 'windowing', 'sprites', 'text', 'shaders', 'assets', 'cameras-2d'], [['3D rendering', '3d']]),
				section('ECS and scenes', 'ecs'),
				nested('Audio, input and UI', 'interaction', ['audio'], [['Input', 'input'], ['UI', 'ui']]),
				section('Physics', 'physics'),
				nested('Web and networking', 'networking', ['overview', 'http-server', 'web-endpoints', 'websockets', 'web-security'], [['Multiplayer', 'multiplayer']]),
				section('Tooling and testing', 'tooling'),
				section('Platforms and publishing', 'platforms'),
				section('Examples', 'examples'),
				section('Reference', 'reference', true),
			],
		}),
	],
});
