// <auto-generated/>
// The web route table of this assembly, generated by Ion.Extensions.Web.Generators from its [Http] and [WebSocket] methods.
#nullable enable
#pragma warning disable CS0612, CS0618, CA2255

namespace Ion.Generated
{
	[global::System.CodeDom.Compiler.GeneratedCode("Ion.Extensions.Web.Generators", "1.0")]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	internal static class IonWebRoutes_TestGame
	{
		/// <summary>The route table: registered before any code of the assembly runs.</summary>
		public static readonly global::Ion.Extensions.Web.WebRouteTable Table = new("TestGame",
			new global::Ion.Extensions.Web.WebRoute[]
			{
				new("GET", "/score", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Route0, (global::Ion.Extensions.Web.WebAccess)0, "ScoreSystem.GetScore"),
				new("GET", "/score/value", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Route1, (global::Ion.Extensions.Web.WebAccess)0, "ScoreSystem.Value"),
				new("POST", "/score/add", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Route2, (global::Ion.Extensions.Web.WebAccess)0, "ScoreSystem.Add"),
				new("GET", "/players/{id}", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Route3, (global::Ion.Extensions.Web.WebAccess)0, "ScoreSystem.Player"),
				new("GET", "/players/{id}/name", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Route4, (global::Ion.Extensions.Web.WebAccess)1, "ScoreSystem.Player"),
				new("PUT", "/players/{id}/name", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Route5, (global::Ion.Extensions.Web.WebAccess)0, "ScoreSystem.Rename"),
				new("POST", "/players", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Route6, (global::Ion.Extensions.Web.WebAccess)0, "ScoreSystem.Create"),
				new("DELETE", "/files/{*path}", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Route7, (global::Ion.Extensions.Web.WebAccess)0, "ScoreSystem.Delete"),
				new("POST", "/raw", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Route8, (global::Ion.Extensions.Web.WebAccess)1, "ScoreSystem.Raw"),
				new("HEAD", "/ping", typeof(global::Game.Outer.Nested), static sp => sp.GetService(typeof(global::Game.Outer.Nested)), Route9, (global::Ion.Extensions.Web.WebAccess)0, "Nested.Ping"),
			},
			new global::Ion.Extensions.Web.WebSocketRoute[]
			{
				new("/events", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Socket0, (global::Ion.Extensions.Web.WebAccess)1, "ScoreSystem.OnEvents"),
				new("/paddle", typeof(global::Game.ScoreSystem), static sp => sp.GetService(typeof(global::Game.ScoreSystem)), Socket1, (global::Ion.Extensions.Web.WebAccess)0, "ScoreSystem.OnPaddle"),
			});

		[global::System.Runtime.CompilerServices.ModuleInitializer]
		internal static void Register() => global::Ion.Extensions.Web.WebRoutes.Register(Table);

		// GET /score: ScoreSystem.GetScore
		private static void Route0(object target, in global::Ion.Extensions.Web.WebRequest request, global::Ion.Extensions.Web.WebResponse response)
		{
			var result = ((global::Game.ScoreSystem)target).GetScore();
			response.Json<global::Game.Info>(result, (JsonOf<global::Game.GameJson, global::Game.Info>.Value ??= global::Ion.Extensions.Web.WebBinding.TypeInfo<global::Game.Info>(global::Game.GameJson.Default)));
		}

		// GET /score/value: ScoreSystem.Value
		private static void Route1(object target, in global::Ion.Extensions.Web.WebRequest request, global::Ion.Extensions.Web.WebResponse response)
		{
			var result = ((global::Game.ScoreSystem)target).Value();
			response.JsonNumber((long)result);
		}

		// POST /score/add: ScoreSystem.Add
		private static void Route2(object target, in global::Ion.Extensions.Web.WebRequest request, global::Ion.Extensions.Web.WebResponse response)
		{
			int p0;
			if (request.TryGetQuery("amount"u8, out var q0))
			{
				if (!global::Ion.Extensions.Web.WebBinding.TryParse<int>(q0, out var p0v))
				{
					response.Error(400, "Invalid value for query parameter 'amount'.");
					return;
				}

				p0 = p0v;
			}
			else
			{
				response.Error(400, "Missing query parameter 'amount'.");
				return;
			}

			bool p1;
			if (request.TryGetQuery("bonus"u8, out var q1))
			{
				if (!global::Ion.Extensions.Web.WebBinding.TryParseBool(q1, out var p1v))
				{
					response.Error(400, "Invalid value for query parameter 'bonus'.");
					return;
				}

				p1 = p1v;
			}
			else
			{
				p1 = (bool)(false);
			}

			string? p2;
			if (request.TryGetQuery("reason"u8, out var q2))
			{
				p2 = global::Ion.Extensions.Web.WebBinding.QueryString(q2);
			}
			else
			{
				p2 = default;
			}

			double p3;
			if (request.TryGetQuery("factor"u8, out var q3))
			{
				if (!global::Ion.Extensions.Web.WebBinding.TryParse<double>(q3, out var p3v))
				{
					response.Error(400, "Invalid value for query parameter 'factor'.");
					return;
				}

				p3 = p3v;
			}
			else
			{
				p3 = (double)(1.5d);
			}

			((global::Game.ScoreSystem)target).Add(p0, p1, p2, p3);
		}

		// GET /players/{id}: ScoreSystem.Player
		private static void Route3(object target, in global::Ion.Extensions.Web.WebRequest request, global::Ion.Extensions.Web.WebResponse response)
		{
			int p0;
			if (!global::Ion.Extensions.Web.WebBinding.TryParse<int>(request.RouteValue(0), out var p0v))
			{
				response.Error(400, "Invalid value for route parameter 'id'.");
				return;
			}

			p0 = p0v;
			var result = ((global::Game.ScoreSystem)target).Player(p0, in request);
			if (result is not null) response.Text(result);
		}

		// GET /players/{id}/name: ScoreSystem.Player
		private static void Route4(object target, in global::Ion.Extensions.Web.WebRequest request, global::Ion.Extensions.Web.WebResponse response)
		{
			int p0;
			if (!global::Ion.Extensions.Web.WebBinding.TryParse<int>(request.RouteValue(0), out var p0v))
			{
				response.Error(400, "Invalid value for route parameter 'id'.");
				return;
			}

			p0 = p0v;
			var result = ((global::Game.ScoreSystem)target).Player(p0, in request);
			if (result is not null) response.Text(result);
		}

		// PUT /players/{id}/name: ScoreSystem.Rename
		private static void Route5(object target, in global::Ion.Extensions.Web.WebRequest request, global::Ion.Extensions.Web.WebResponse response)
		{
			global::System.Guid p0;
			if (!global::Ion.Extensions.Web.WebBinding.TryParse<global::System.Guid>(request.RouteValue(0), out var p0v))
			{
				response.Error(400, "Invalid value for route parameter 'id'.");
				return;
			}

			p0 = p0v;
			var p1 = global::Ion.Extensions.Web.WebBinding.BodyString(in request);
			var p2 = response;
			((global::Game.ScoreSystem)target).Rename(p0, p1, ref p2);
		}

		// POST /players: ScoreSystem.Create
		private static void Route6(object target, in global::Ion.Extensions.Web.WebRequest request, global::Ion.Extensions.Web.WebResponse response)
		{
			if (!global::Ion.Extensions.Web.WebBinding.TryReadJson<global::Game.Payload>(request.Body, (JsonOf<global::Game.GameJson, global::Game.Payload>.Value ??= global::Ion.Extensions.Web.WebBinding.TypeInfo<global::Game.Payload>(global::Game.GameJson.Default)), out var p0, out var e0))
			{
				response.Error(400, e0!);
				return;
			}

			var result = ((global::Game.ScoreSystem)target).Create(p0!);
			response.Json<global::Game.Payload>(result!, (JsonOf<global::Game.GameJson, global::Game.Payload>.Value ??= global::Ion.Extensions.Web.WebBinding.TypeInfo<global::Game.Payload>(global::Game.GameJson.Default)));
		}

		// DELETE /files/{*path}: ScoreSystem.Delete
		private static void Route7(object target, in global::Ion.Extensions.Web.WebRequest request, global::Ion.Extensions.Web.WebResponse response)
		{
			var p0 = global::Ion.Extensions.Web.WebBinding.RouteString(request.RouteValue(0));
			int? p1;
			if (request.TryGetQuery("limit"u8, out var q1))
			{
				if (!global::Ion.Extensions.Web.WebBinding.TryParse<int>(q1, out var p1v))
				{
					response.Error(400, "Invalid value for query parameter 'limit'.");
					return;
				}

				p1 = p1v;
			}
			else
			{
				p1 = default;
			}

			var result = ((global::Game.ScoreSystem)target).Delete(p0, p1);
			if (result is { } value) response.JsonNumber((long)value);
			else response.JsonNull();
		}

		// POST /raw: ScoreSystem.Raw
		private static void Route8(object target, in global::Ion.Extensions.Web.WebRequest request, global::Ion.Extensions.Web.WebResponse response)
		{
			((global::Game.ScoreSystem)target).Raw(request.Body, response);
		}

		// HEAD /ping: Nested.Ping
		private static void Route9(object target, in global::Ion.Extensions.Web.WebRequest request, global::Ion.Extensions.Web.WebResponse response)
		{
			((global::Game.Outer.Nested)target).Ping();
		}

		// WebSocket /events: ScoreSystem.OnEvents
		private static void Socket0(object target, in global::Ion.Extensions.Web.WebSocketMessage message) =>
			((global::Game.ScoreSystem)target).OnEvents(in message);

		// WebSocket /paddle: ScoreSystem.OnPaddle
		private static void Socket1(object target, in global::Ion.Extensions.Web.WebSocketMessage message) =>
			((global::Game.ScoreSystem)target).OnPaddle(message);

		/// <summary>The JSON type information of a context, looked up once.</summary>
		private static class JsonOf<TContext, T>
		{
			public static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>? Value;
		}
	}
}
